-- VNPAY sandbox only. The application verifier is the trust boundary; its separate
-- database role can invoke the result command, never arbitrary table mutations.
DO $roles$ BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='smart_cinema_payment_system') THEN
        CREATE ROLE smart_cinema_payment_system NOLOGIN;
    END IF;
END $roles$;
ALTER TABLE payment_transactions DROP CONSTRAINT chk_payment_transactions_initiation_stage;
ALTER TABLE payment_transactions ADD COLUMN merchant_code varchar(8),
    ADD COLUMN environment varchar(10), ADD COLUMN merchant_reference varchar(100),
    ADD COLUMN submitted_amount numeric(12,0), ADD COLUMN provider_created_at timestamptz,
    ADD COLUMN provider_expires_at timestamptz, ADD COLUMN return_url varchar(255),
    ADD COLUMN client_ip varchar(45), ADD COLUMN reconciliation_required boolean NOT NULL DEFAULT false,
    ADD COLUMN next_query_at timestamptz;
ALTER TABLE payment_transactions ADD CONSTRAINT uq_payment_transactions_submission
    UNIQUE(provider,environment,merchant_code,merchant_reference);
ALTER TABLE payment_transactions DROP CONSTRAINT uq_payment_transactions_provider_external;
ALTER TABLE payment_transactions ADD CONSTRAINT uq_payment_transactions_provider_external
    UNIQUE(provider,environment,merchant_code,external_reference);
ALTER TABLE payment_transactions ADD CONSTRAINT chk_payment_transactions_binding CHECK ((
    (provider IS NULL AND currency IS NULL AND environment IS NULL AND merchant_code IS NULL
        AND merchant_reference IS NULL AND submitted_amount IS NULL AND provider_created_at IS NULL
        AND provider_expires_at IS NULL AND return_url IS NULL AND client_ip IS NULL AND status='INITIATED'
        AND external_reference IS NULL)
    OR (provider='VNPAY' AND currency='VND' AND environment='SANDBOX' AND merchant_code ~ '^[A-Za-z0-9]{8}$'
        AND merchant_reference ~ '^P[0-9a-f]{32}$' AND submitted_amount IS NOT NULL
        AND amount>0 AND trunc(amount)=amount AND submitted_amount=amount*100
        AND provider_created_at IS NOT NULL AND isfinite(provider_created_at)
        AND provider_expires_at IS NOT NULL AND isfinite(provider_expires_at)
        AND provider_expires_at>provider_created_at AND return_url IS NOT NULL AND client_ip IS NOT NULL)) IS TRUE);
ALTER TABLE payment_transactions ADD CONSTRAINT chk_payment_transactions_result CHECK (
    (status IN ('INITIATED','PENDING') AND completed_at IS NULL)
    OR (status IN ('SUCCESS','FAILED','CANCELLED') AND completed_at IS NOT NULL
        AND isfinite(completed_at) AND completed_at>=initiated_at));
ALTER TABLE payment_transactions ADD CONSTRAINT chk_payment_transactions_metadata CHECK(jsonb_typeof(provider_metadata)='object');

CREATE TABLE payment_evidence (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id bigint NOT NULL REFERENCES payment_transactions(id) ON DELETE NO ACTION,
    source varchar(10) NOT NULL CHECK(source IN ('IPN','QUERY')),
    digest varchar(64) NOT NULL CHECK(digest ~ '^[0-9a-f]{64}$'),
    result varchar(20) NOT NULL CHECK(result IN ('SUCCESS','FAILED','CANCELLED','PENDING','RECONCILE')),
    response_code varchar(4) NOT NULL, transaction_status varchar(4) NOT NULL,
    external_reference varchar(255), observed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    UNIQUE(payment_id,source,digest)
);
CREATE TABLE payment_reconciliations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id bigint NOT NULL REFERENCES payment_transactions(id) ON DELETE NO ACTION,
    reason varchar(50) NOT NULL, evidence_id bigint REFERENCES payment_evidence(id),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_observed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    resolved_at timestamptz, resolved_by_user_id bigint REFERENCES users(id), resolution_note varchar(1000),
    CHECK((resolved_at IS NULL AND resolved_by_user_id IS NULL AND resolution_note IS NULL)
        OR (resolved_at IS NOT NULL AND isfinite(resolved_at) AND resolved_at>=created_at
        AND resolved_by_user_id IS NOT NULL AND length(btrim(resolution_note))>0) IS TRUE),
    UNIQUE(payment_id,reason)
);
CREATE TABLE tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_seat_id bigint NOT NULL UNIQUE REFERENCES booking_seats(id) ON DELETE NO ACTION,
    ticket_code varchar(64) NOT NULL UNIQUE CHECK(btrim(ticket_code)<>''),
    status varchar(20) NOT NULL CHECK(status IN ('VALID','CHECKED_IN','EXPIRED','CANCELLED')),
    issued_at timestamptz NOT NULL CHECK(isfinite(issued_at)),
    checked_in_at timestamptz, checked_in_by_user_id bigint REFERENCES users(id),
    CHECK((status='CHECKED_IN' AND checked_in_at IS NOT NULL AND checked_in_by_user_id IS NOT NULL AND checked_in_at>=issued_at)
        OR (status<>'CHECKED_IN' AND checked_in_at IS NULL AND checked_in_by_user_id IS NULL))
);
CREATE TABLE audit_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id bigint REFERENCES users(id), action varchar(100) NOT NULL,
    resource_type varchar(50) NOT NULL, resource_id bigint NOT NULL,
    occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(), metadata jsonb NOT NULL,
    CHECK(jsonb_typeof(metadata)='object'),
    CHECK(actor_user_id IS NOT NULL OR (jsonb_typeof(metadata->'system_actor')='string'
        AND length(metadata->>'system_actor')>0) IS TRUE)
);
ALTER TABLE bookings DROP CONSTRAINT chk_bookings_pre_payment_stage;
ALTER TABLE booking_seats DROP CONSTRAINT chk_booking_seats_pre_payment_stage;
ALTER TABLE seat_holds DROP CONSTRAINT chk_seat_holds_pre_payment_stage;

DO $migration$
DECLARE ns text:=current_schema(); source text; anchor text; ddl text:=$definitions$
CREATE FUNCTION app.payment_settlement_eligible(p_booking bigint) RETURNS boolean
LANGUAGE sql VOLATILE SET search_path=pg_catalog,pg_temp AS $body$
 SELECT EXISTS(SELECT 1 FROM app.bookings b JOIN app.showtimes s ON s.id=b.showtime_id
 JOIN app.halls h ON h.id=s.hall_id JOIN app.cinemas c ON c.id=h.cinema_id JOIN app.movies m ON m.id=s.movie_id
 WHERE b.id=p_booking AND b.status='PENDING' AND b.payment_started_at IS NOT NULL AND b.expires_at>clock_timestamp()
 AND s.status='OPEN_FOR_BOOKING' AND s.start_time>clock_timestamp() AND s.booking_cut_off>clock_timestamp()
 AND h.status='ACTIVE' AND c.status='ACTIVE' AND m.status='PUBLISHED'
 AND b.seat_amount=(SELECT coalesce(sum(final_price),0) FROM app.booking_seats WHERE booking_id=b.id)
 AND b.concession_amount=(SELECT coalesce(sum(total_price),0) FROM app.booking_concessions WHERE booking_id=b.id)
 AND EXISTS(SELECT 1 FROM app.booking_seats WHERE booking_id=b.id)
 AND NOT EXISTS(SELECT 1 FROM app.booking_seats bs JOIN app.seats seat ON seat.id=bs.seat_id
 JOIN app.showtime_seats ss ON ss.showtime_id=bs.showtime_id AND ss.seat_id=bs.seat_id
 LEFT JOIN app.seat_holds sh ON sh.booking_id=b.id AND sh.seat_id=bs.seat_id AND sh.showtime_id=b.showtime_id
 WHERE bs.booking_id=b.id AND (NOT ss.is_sellable OR seat.physical_status<>'ACTIVE'
 OR sh.id IS NULL OR sh.status<>'ACTIVE' OR sh.expires_at<=clock_timestamp() OR sh.user_id<>b.customer_id
 OR EXISTS(SELECT 1 FROM app.booking_seats sold WHERE sold.showtime_id=bs.showtime_id AND sold.seat_id=bs.seat_id AND sold.sold_at IS NOT NULL))))
$body$;

CREATE OR REPLACE FUNCTION app.assert_payment_freeze() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_id bigint; b app.bookings%ROWTYPE; v_count bigint;
BEGIN
 IF TG_TABLE_NAME='bookings' THEN v_id:=coalesce(NEW.id,OLD.id); ELSE v_id:=coalesce(NEW.booking_id,OLD.booking_id); END IF;
 SELECT * INTO b FROM app.bookings WHERE id=v_id;
 SELECT count(*) INTO v_count FROM app.payment_transactions WHERE booking_id=v_id;
 IF b.id IS NULL OR (b.payment_started_at IS NULL AND v_count<>0)
 OR (b.payment_started_at IS NOT NULL AND (v_count=0 OR b.payment_started_at IS DISTINCT FROM
 (SELECT min(initiated_at) FROM app.payment_transactions WHERE booking_id=v_id)))
 OR EXISTS(SELECT 1 FROM app.payment_transactions WHERE booking_id=v_id AND amount<>b.final_amount) THEN
 RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid permanent Payment freeze'; END IF;
 RETURN NULL;
END $body$;

CREATE OR REPLACE FUNCTION app.guard_payment_transaction() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
 IF current_user<>'smart_cinema_hold_owner' OR TG_OP='DELETE' THEN
 RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Protected Payment'; END IF;
 IF TG_OP='INSERT' THEN
  IF NEW.status<>'INITIATED' OR NEW.provider IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid initial Payment'; END IF;
  IF EXISTS(SELECT 1 FROM app.bookings WHERE id=NEW.booking_id AND payment_started_at IS NULL) THEN
   PERFORM app.validate_payment_composition(NEW.booking_id);
  ELSIF NOT app.payment_settlement_eligible(NEW.booking_id) OR EXISTS(SELECT 1 FROM app.payment_transactions
    WHERE booking_id=NEW.booking_id AND (status NOT IN ('FAILED','CANCELLED') OR reconciliation_required)) THEN
   RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Payment retry unavailable';
  END IF;
  IF NOT EXISTS(SELECT 1 FROM app.bookings WHERE id=NEW.booking_id AND final_amount=NEW.amount
   AND created_at<=NEW.initiated_at AND NEW.initiated_at<expires_at) OR NEW.initiated_at>clock_timestamp() THEN
   RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid Payment origin'; END IF;
 ELSE
  IF (NEW.id,NEW.booking_id,NEW.internal_reference,NEW.amount,NEW.initiated_at) IS DISTINCT FROM
   (OLD.id,OLD.booking_id,OLD.internal_reference,OLD.amount,OLD.initiated_at)
   OR (OLD.provider IS NOT NULL AND (to_jsonb(NEW)-ARRAY['status','completed_at','external_reference','reconciliation_required','next_query_at'])
     IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['status','completed_at','external_reference','reconciliation_required','next_query_at']))
   OR (OLD.external_reference IS NOT NULL AND NEW.external_reference IS DISTINCT FROM OLD.external_reference)
   OR (OLD.status='SUCCESS' AND NEW.status<>'SUCCESS') THEN
   RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Immutable Payment identity'; END IF;
  IF NEW.status IN ('SUCCESS','FAILED','CANCELLED') AND NOT EXISTS(SELECT 1 FROM app.payment_evidence
    WHERE payment_id=NEW.id AND result=NEW.status) THEN
   RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Payment requires trusted evidence'; END IF;
 END IF;
 RETURN NEW;
END $body$;

CREATE FUNCTION app.guard_payment_record() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
 IF TG_TABLE_NAME='payment_reconciliations' AND TG_OP='UPDATE' AND current_user='smart_cinema_hold_owner' THEN
  IF NEW.last_observed_at>=OLD.last_observed_at AND
   (to_jsonb(NEW)-ARRAY['last_observed_at','resolved_at','resolved_by_user_id','resolution_note'])=
   (to_jsonb(OLD)-ARRAY['last_observed_at','resolved_at','resolved_by_user_id','resolution_note']) THEN RETURN NEW; END IF;
 END IF;
 IF current_user<>'smart_cinema_hold_owner' OR TG_OP<>'INSERT' THEN
  RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Append-only Payment record'; END IF;
 RETURN NEW;
END $body$;
CREATE TRIGGER trg_payment_evidence_guard BEFORE INSERT OR UPDATE OR DELETE ON app.payment_evidence FOR EACH ROW EXECUTE FUNCTION app.guard_payment_record();
CREATE TRIGGER trg_payment_reconciliations_guard BEFORE INSERT OR UPDATE OR DELETE ON app.payment_reconciliations FOR EACH ROW EXECUTE FUNCTION app.guard_payment_record();
CREATE TRIGGER trg_audit_records_guard BEFORE INSERT OR UPDATE OR DELETE ON app.audit_records FOR EACH ROW EXECUTE FUNCTION app.guard_payment_record();
CREATE TRIGGER trg_tickets_guard BEFORE INSERT OR UPDATE OR DELETE ON app.tickets FOR EACH ROW EXECUTE FUNCTION app.guard_payment_record();

CREATE FUNCTION app.assert_paid_aggregate() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_booking bigint; b app.bookings%ROWTYPE;
BEGIN
 IF TG_TABLE_NAME='tickets' THEN SELECT booking_id INTO v_booking FROM app.booking_seats WHERE id=coalesce(NEW.booking_seat_id,OLD.booking_seat_id);
 ELSIF TG_TABLE_NAME='bookings' THEN v_booking:=coalesce(NEW.id,OLD.id);
 ELSE v_booking:=coalesce(NEW.booking_id,OLD.booking_id); END IF;
 IF v_booking IS NULL THEN RETURN NULL; END IF;
 SELECT * INTO b FROM app.bookings WHERE id=v_booking;
 IF b.status='PAID' THEN
  IF NOT EXISTS(SELECT 1 FROM app.payment_transactions WHERE booking_id=b.id AND status='SUCCESS' AND amount=b.final_amount)
   OR NOT EXISTS(SELECT 1 FROM app.audit_records WHERE resource_type='BOOKING' AND resource_id=b.id AND action='SALE_FINALIZED')
   OR EXISTS(SELECT 1 FROM app.booking_seats bs LEFT JOIN app.tickets t ON t.booking_seat_id=bs.id
     LEFT JOIN app.seat_holds h ON h.booking_id=bs.booking_id AND h.seat_id=bs.seat_id
     WHERE bs.booking_id=b.id AND (bs.sold_at IS DISTINCT FROM b.paid_at OR t.id IS NULL
       OR t.issued_at IS DISTINCT FROM b.paid_at OR h.status IS DISTINCT FROM 'CONSUMED')) THEN
   RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Incomplete paid aggregate'; END IF;
 ELSE
  IF EXISTS(SELECT 1 FROM app.booking_seats bs LEFT JOIN app.tickets t ON t.booking_seat_id=bs.id
     WHERE bs.booking_id=b.id AND (bs.sold_at IS NOT NULL OR t.id IS NOT NULL))
   OR EXISTS(SELECT 1 FROM app.seat_holds WHERE booking_id=b.id AND status='CONSUMED') THEN
   RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Unpaid entitlement'; END IF;
 END IF;
 RETURN NULL;
END $body$;
CREATE CONSTRAINT TRIGGER ct_paid_booking AFTER INSERT OR UPDATE OR DELETE ON app.bookings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_paid_aggregate();
CREATE CONSTRAINT TRIGGER ct_paid_seat AFTER INSERT OR UPDATE OR DELETE ON app.booking_seats DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_paid_aggregate();
CREATE CONSTRAINT TRIGGER ct_paid_hold AFTER INSERT OR UPDATE OR DELETE ON app.seat_holds DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_paid_aggregate();
CREATE CONSTRAINT TRIGGER ct_paid_ticket AFTER INSERT OR UPDATE OR DELETE ON app.tickets DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_paid_aggregate();
CREATE CONSTRAINT TRIGGER ct_paid_payment AFTER INSERT OR UPDATE OR DELETE ON app.payment_transactions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_paid_aggregate();

CREATE FUNCTION app.bind_vnpay_submission(p_payment bigint,p_user bigint,p_merchant text,p_return text,p_ip text,p_order text DEFAULT 'other')
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE b app.bookings%ROWTYPE; p app.payment_transactions%ROWTYPE; v_now timestamptz; v_end timestamptz;
BEGIN
 SELECT b0.* INTO b FROM app.bookings b0 JOIN app.payment_transactions p0 ON p0.booking_id=b0.id WHERE p0.id=p_payment AND b0.customer_id=p_user;
 IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Payment unavailable'; END IF;
 PERFORM app.lock_hold_context(b.showtime_id,p_user); PERFORM app.lock_booking_resources(b.showtime_id);
 PERFORM id FROM app.promotions WHERE id=b.promotion_id FOR UPDATE;
 SELECT * INTO p FROM app.payment_transactions WHERE id=p_payment FOR UPDATE;
 IF NOT app.payment_settlement_eligible(b.id) OR p.status NOT IN ('INITIATED','PENDING') OR p.reconciliation_required
 OR EXISTS(SELECT 1 FROM app.payment_transactions other WHERE other.booking_id=b.id AND other.id<>p.id
   AND (other.status='SUCCESS' OR other.reconciliation_required)) THEN
  RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Submission unavailable'; END IF;
 IF p.provider IS NOT NULL THEN
  IF p.merchant_code<>p_merchant OR p.return_url<>p_return OR p.provider_expires_at<=clock_timestamp() THEN
   RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Submission binding conflict'; END IF;
  RETURN p.id;
 END IF;
 v_now:=date_trunc('second',clock_timestamp()); v_end:=date_trunc('second',b.expires_at);
 IF p.amount<=0 OR trunc(p.amount)<>p.amount OR p.amount*100>999999999999 OR v_end<=v_now THEN
  RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Unsupported provider amount or deadline'; END IF;
 UPDATE app.payment_transactions SET provider='VNPAY',environment='SANDBOX',currency='VND',merchant_code=p_merchant,
  merchant_reference=replace(internal_reference,'-',''),submitted_amount=amount*100,provider_created_at=v_now,
  provider_expires_at=v_end,return_url=p_return,client_ip=p_ip,status='PENDING',
  provider_metadata=jsonb_build_object('order_type',p_order) WHERE id=p.id;
 RETURN p.id;
END $body$;

CREATE FUNCTION app.record_vnpay_result(p_merchant text,p_reference text,p_amount numeric,p_external text,
 p_source text,p_digest text,p_result text,p_code text,p_status text) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE p app.payment_transactions%ROWTYPE; b app.bookings%ROWTYPE; v_evidence bigint; v_reason text;
 v_now timestamptz; v_limit bigint; v_used bigint;
BEGIN
 SELECT * INTO p FROM app.payment_transactions WHERE provider='VNPAY' AND environment='SANDBOX'
  AND merchant_code=p_merchant AND merchant_reference=p_reference;
 IF NOT FOUND THEN RETURN '01'; END IF;
 IF p_amount IS DISTINCT FROM p.submitted_amount THEN RETURN '04'; END IF;
 SELECT * INTO b FROM app.bookings WHERE id=p.booking_id;
 PERFORM app.lock_hold_context(b.showtime_id,NULL); PERFORM app.lock_booking_resources(b.showtime_id);
 SELECT usage_limit INTO v_limit FROM app.promotions WHERE id=b.promotion_id FOR UPDATE;
 SELECT * INTO p FROM app.payment_transactions WHERE id=p.id FOR UPDATE;
 SELECT * INTO b FROM app.bookings WHERE id=p.booking_id;
 INSERT INTO app.payment_evidence(payment_id,source,digest,result,response_code,transaction_status,external_reference)
 VALUES(p.id,p_source,p_digest,p_result,p_code,p_status,p_external) ON CONFLICT DO NOTHING RETURNING id INTO v_evidence;
 IF v_evidence IS NULL THEN RETURN '02'; END IF;
 IF (p.external_reference IS NOT NULL AND p_external IS NOT NULL AND p.external_reference<>p_external)
 OR EXISTS(SELECT 1 FROM app.payment_transactions other WHERE other.id<>p.id AND other.provider='VNPAY'
   AND other.environment='SANDBOX' AND other.merchant_code=p_merchant AND other.external_reference=p_external) THEN v_reason:='REFERENCE_CONFLICT';
 ELSIF p_result='RECONCILE' THEN v_reason:='SPECIAL_RESULT';
 ELSIF p.status IN ('FAILED','CANCELLED') AND p_result<>p.status THEN v_reason:='TERMINAL_CORRECTION';
 ELSIF p.status='SUCCESS' AND p_result<>'SUCCESS' THEN v_reason:='CONTRADICTORY_RESULT';
 ELSIF p.reconciliation_required AND p.status<>'SUCCESS' THEN v_reason:='EXISTING_RECONCILIATION';
 ELSIF p_result='SUCCESS' AND p.status<>'SUCCESS' AND EXISTS(SELECT 1 FROM app.payment_transactions other
   WHERE other.booking_id=b.id AND other.id<>p.id AND (other.status='SUCCESS' OR other.reconciliation_required)) THEN
  v_reason:='ADDITIONAL_FINANCIAL_SUCCESS';
 END IF;
 IF v_reason IS NULL OR (p_result='SUCCESS' AND v_reason IN ('TERMINAL_CORRECTION','EXISTING_RECONCILIATION','ADDITIONAL_FINANCIAL_SUCCESS')) THEN
  UPDATE app.payment_transactions SET status=CASE WHEN p.status='SUCCESS' THEN 'SUCCESS' ELSE p_result END,
   completed_at=CASE WHEN p_result IN ('SUCCESS','FAILED','CANCELLED') THEN coalesce(completed_at,clock_timestamp()) ELSE completed_at END,
   external_reference=coalesce(external_reference,p_external) WHERE id=p.id;
 END IF;
 IF p_result='SUCCESS' AND v_reason IS NULL AND b.status<>'PAID' THEN
  SELECT count(*) INTO v_used FROM app.bookings WHERE promotion_id=b.promotion_id AND status='PAID';
  IF NOT app.payment_settlement_eligible(b.id) THEN v_reason:='FULFILLMENT_UNAVAILABLE';
  ELSIF v_limit IS NOT NULL AND v_used>=v_limit THEN v_reason:='PROMOTION_EXHAUSTED';
  ELSE
   v_now:=clock_timestamp();
   UPDATE app.bookings SET status='PAID',paid_at=v_now,booking_qr_token=replace(gen_random_uuid()::text,'-','')||replace(gen_random_uuid()::text,'-','') WHERE id=b.id;
   UPDATE app.booking_seats SET sold_at=v_now WHERE booking_id=b.id;
   UPDATE app.seat_holds SET status='CONSUMED' WHERE booking_id=b.id;
   INSERT INTO app.tickets(booking_seat_id,ticket_code,status,issued_at)
    SELECT id,'T-'||replace(gen_random_uuid()::text,'-',''),'VALID',v_now FROM app.booking_seats WHERE booking_id=b.id;
   INSERT INTO app.audit_records(action,resource_type,resource_id,metadata)
    VALUES('SALE_FINALIZED','BOOKING',b.id,jsonb_build_object('system_actor','VNPAY','payment_id',p.id::text,'evidence_id',v_evidence::text));
  END IF;
 ELSIF p_result='SUCCESS' AND b.status='PAID' AND p.status<>'SUCCESS' THEN v_reason:='ADDITIONAL_FINANCIAL_SUCCESS';
 END IF;
 IF v_reason IS NOT NULL THEN
  UPDATE app.payment_transactions SET reconciliation_required=true WHERE id=p.id;
  INSERT INTO app.payment_reconciliations(payment_id,reason,evidence_id) VALUES(p.id,v_reason,v_evidence)
   ON CONFLICT(payment_id,reason) DO UPDATE SET last_observed_at=clock_timestamp(),resolved_at=NULL,resolved_by_user_id=NULL,resolution_note=NULL;
 END IF;
 PERFORM app.expire_booking_aggregates(b.showtime_id);
 INSERT INTO app.audit_records(action,resource_type,resource_id,metadata) VALUES('PAYMENT_OBSERVED','PAYMENT',p.id,
  jsonb_build_object('system_actor','VNPAY','evidence_id',v_evidence::text,'result',p_result,'reason',v_reason));
 RETURN '00';
END $body$;
-- Scheduling-only claim: holds no parent/domain locks and commits before network I/O.
CREATE FUNCTION app.claim_vnpay_queries(p_merchant text,p_delay interval,p_horizon interval)
RETURNS SETOF app.payment_transactions LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE p app.payment_transactions%ROWTYPE;
BEGIN
 IF p_delay<=interval '0 seconds' OR p_horizon<=interval '0 seconds' THEN
  RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='Invalid query schedule'; END IF;
 FOR p IN SELECT * FROM app.payment_transactions WHERE merchant_code=p_merchant AND environment='SANDBOX'
  AND status='PENDING' AND NOT reconciliation_required AND coalesce(next_query_at,provider_created_at)<=clock_timestamp()
  ORDER BY id LIMIT 20 FOR UPDATE SKIP LOCKED LOOP
  IF p.provider_created_at+p_horizon<=clock_timestamp() THEN
   UPDATE app.payment_transactions SET reconciliation_required=true WHERE id=p.id;
   INSERT INTO app.payment_reconciliations(payment_id,reason) VALUES(p.id,'QUERY_HORIZON') ON CONFLICT DO NOTHING;
   INSERT INTO app.audit_records(action,resource_type,resource_id,metadata) VALUES('QUERY_ESCALATED','PAYMENT',p.id,
    jsonb_build_object('system_actor','VNPAY_QUERY'));
  ELSE
   UPDATE app.payment_transactions SET next_query_at=clock_timestamp()+p_delay WHERE id=p.id;
   RETURN NEXT p;
  END IF;
 END LOOP;
END $body$;
CREATE FUNCTION app.resolve_payment_reconciliation(p_case bigint,p_operator bigint,p_note text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
 PERFORM id FROM app.users WHERE id=p_operator AND role='ADMIN' AND status='ACTIVE' FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0004',MESSAGE='Authorized operator required'; END IF;
 IF p_note IS NULL OR btrim(p_note)='' OR length(p_note)>1000 THEN RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='Resolution evidence required'; END IF;
 UPDATE app.payment_reconciliations SET resolved_at=clock_timestamp(),resolved_by_user_id=p_operator,resolution_note=p_note
 WHERE id=p_case AND resolved_at IS NULL;
 IF FOUND THEN INSERT INTO app.audit_records(actor_user_id,action,resource_type,resource_id,metadata)
 VALUES(p_operator,'RECONCILIATION_RESOLVED','PAYMENT_RECONCILIATION',p_case,jsonb_build_object('resolution_note',p_note)); END IF;
 -- Operator resolution never manufactures a financial/Booking transition or refunds.
END $body$;
$definitions$;
BEGIN
 EXECUTE replace(ddl,'app.',format('%I.',ns));
 -- Retain existing insert/snapshot/ownership guards; add only the paid transition.
 source:=pg_get_functiondef(format('%I.guard_booking()',ns)::regprocedure);
 anchor:='ELSIF NEW.status=OLD.status THEN';
 IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected Booking guard'; END IF;
 source:=replace(source,anchor,format($patch$
 ELSIF OLD.status='PENDING' AND NEW.status='PAID' THEN
  IF (to_jsonb(NEW)-ARRAY['status','paid_at','booking_qr_token']) IS DISTINCT FROM
    (to_jsonb(OLD)-ARRAY['status','paid_at','booking_qr_token']) OR NOT %1$I.payment_settlement_eligible(OLD.id)
    OR NOT EXISTS(SELECT 1 FROM %1$I.payment_transactions WHERE booking_id=OLD.id AND status='SUCCESS') THEN
   RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid paid transition'; END IF;
 ELSIF NEW.status=OLD.status THEN
 $patch$,ns)); EXECUTE source;
 source:=pg_get_functiondef(format('%I.guard_booking_seat()',ns)::regprocedure);
 anchor:='BEGIN';
 source:=replace(source,anchor,format($patch$BEGIN
 IF TG_OP='UPDATE' AND current_user='smart_cinema_hold_owner' AND OLD.sold_at IS NULL
 AND NEW.sold_at IS NOT NULL AND (to_jsonb(NEW)-'sold_at')=(to_jsonb(OLD)-'sold_at')
 AND EXISTS(SELECT 1 FROM %1$I.bookings WHERE id=NEW.booking_id AND status='PAID' AND paid_at=NEW.sold_at) THEN RETURN NEW; END IF;
 $patch$,ns)); EXECUTE source;
 source:=pg_get_functiondef(format('%I.guard_seat_hold()',ns)::regprocedure);
 source:=replace(source,'BEGIN',format($patch$BEGIN
 IF TG_OP='UPDATE' AND current_user='smart_cinema_hold_owner' AND OLD.status='ACTIVE' AND NEW.status='CONSUMED'
 AND (to_jsonb(NEW)-'status')=(to_jsonb(OLD)-'status')
 AND EXISTS(SELECT 1 FROM %1$I.bookings WHERE id=NEW.booking_id AND status='PAID') THEN RETURN NEW; END IF;
 $patch$,ns)); EXECUTE source;
 source:=pg_get_functiondef(format('%I.assert_booking()',ns)::regprocedure);
 anchor:='OR bs.sold_at IS NOT NULL';
 IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected Booking assertion'; END IF;
 source:=replace(source,anchor,'OR (b.status<>''PAID'' AND bs.sold_at IS NOT NULL)'); EXECUTE source;
 -- Retry insertion uses the new guard; first initiation remains the V9 transaction.
 source:=pg_get_functiondef(format('%I.initiate_payment(bigint,bigint)',ns)::regprocedure);
 source:=replace(source,'status=''INITIATED''','status IN (''INITIATED'',''PENDING'')');
 anchor:='IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE=''23514'',MESSAGE=''Missing unresolved Payment''; END IF;';
 IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected initiation retry branch'; END IF;
 source:=replace(source,anchor,format($patch$IF NOT FOUND THEN
 INSERT INTO %1$I.payment_transactions(booking_id,internal_reference,amount,initiated_at)
 VALUES(p_booking,'P-'||replace(gen_random_uuid()::text,'-',''),b.final_amount,clock_timestamp()) RETURNING id INTO v_id;
 END IF;$patch$,ns)); EXECUTE source;
END $migration$;

DO $permissions$
DECLARE ns text:=current_schema(); item text; proc record;
BEGIN
 FOREACH item IN ARRAY ARRAY['payment_evidence','payment_reconciliations','tickets','audit_records'] LOOP
  EXECUTE format('ALTER TABLE %I.%I OWNER TO smart_cinema_hold_owner',ns,item);
  EXECUTE format('REVOKE ALL ON %I.%I FROM PUBLIC',ns,item);
  EXECUTE format('GRANT SELECT ON %I.%I TO smart_cinema_payment_system',ns,item);
 END LOOP;
 EXECUTE format('GRANT SELECT ON %I.tickets TO smart_cinema_hold_runtime',ns);
 EXECUTE format('GRANT SELECT(payment_id,source,result,observed_at) ON %I.payment_evidence TO smart_cinema_hold_runtime',ns);
 EXECUTE format('GRANT USAGE ON SCHEMA %I TO smart_cinema_payment_system',ns);
 EXECUTE format('GRANT SELECT ON %I.payment_transactions,%I.bookings TO smart_cinema_payment_system',ns,ns);
 FOR proc IN SELECT p.oid::regprocedure AS signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
 WHERE n.nspname=ns AND p.proname IN ('payment_settlement_eligible','guard_payment_record','assert_paid_aggregate','bind_vnpay_submission','record_vnpay_result','claim_vnpay_queries','resolve_payment_reconciliation') LOOP
  EXECUTE format('ALTER FUNCTION %s OWNER TO smart_cinema_hold_owner',proc.signature);
  EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',proc.signature);
 END LOOP;
 EXECUTE format('GRANT EXECUTE ON FUNCTION %I.bind_vnpay_submission(bigint,bigint,text,text,text,text) TO smart_cinema_hold_runtime',ns);
 EXECUTE format('GRANT EXECUTE ON FUNCTION %I.record_vnpay_result(text,text,numeric,text,text,text,text,text,text) TO smart_cinema_payment_system',ns);
 EXECUTE format('GRANT EXECUTE ON FUNCTION %I.claim_vnpay_queries(text,interval,interval) TO smart_cinema_payment_system',ns);
 EXECUTE format('GRANT EXECUTE ON FUNCTION %I.resolve_payment_reconciliation(bigint,bigint,text) TO smart_cinema_payment_system',ns);
END $permissions$;
