CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_users_email UNIQUE (email),
    CONSTRAINT chk_users_email_normalized
        CHECK (email = LOWER(BTRIM(email)) AND email <> ''),
    CONSTRAINT chk_users_password_hash_not_blank
        CHECK (BTRIM(password_hash) <> ''),
    CONSTRAINT chk_users_full_name_not_blank
        CHECK (BTRIM(full_name) <> ''),
    CONSTRAINT chk_users_phone_not_blank
        CHECK (BTRIM(phone) <> ''),
    CONSTRAINT chk_users_role
        CHECK (role IN ('CUSTOMER', 'STAFF', 'MANAGER', 'ADMIN')),
    CONSTRAINT chk_users_status_not_blank
        CHECK (BTRIM(status) <> '')
);
