CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    duration INTEGER NOT NULL,
    release_date DATE,
    age_rating VARCHAR(20),
    language VARCHAR(100),
    poster VARCHAR(2048),
    trailer VARCHAR(2048),
    status VARCHAR(30) NOT NULL,

    CONSTRAINT pk_movies PRIMARY KEY (id),
    CONSTRAINT chk_movies_title_not_blank CHECK (BTRIM(title) <> ''),
    CONSTRAINT chk_movies_description_not_blank CHECK (description IS NULL OR BTRIM(description) <> ''),
    CONSTRAINT chk_movies_duration_positive CHECK (duration > 0),
    CONSTRAINT chk_movies_release_date_finite CHECK (release_date IS NULL OR ISFINITE(release_date)),
    CONSTRAINT chk_movies_age_rating_not_blank CHECK (age_rating IS NULL OR BTRIM(age_rating) <> ''),
    CONSTRAINT chk_movies_language_not_blank CHECK (language IS NULL OR BTRIM(language) <> ''),
    CONSTRAINT chk_movies_poster_not_blank CHECK (poster IS NULL OR BTRIM(poster) <> ''),
    CONSTRAINT chk_movies_trailer_not_blank CHECK (trailer IS NULL OR BTRIM(trailer) <> ''),
    CONSTRAINT chk_movies_status_not_blank CHECK (BTRIM(status) <> ''),
    CONSTRAINT chk_movies_status_format CHECK (status ~ '^[A-Z][A-Z0-9_]*$')
);

CREATE TABLE genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,

    CONSTRAINT pk_genres PRIMARY KEY (id),
    CONSTRAINT chk_genres_name_not_blank CHECK (BTRIM(name) <> '')
);

CREATE TABLE movie_genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,

    CONSTRAINT pk_movie_genres PRIMARY KEY (id),
    CONSTRAINT fk_movie_genres_movie FOREIGN KEY (movie_id)
        REFERENCES movies (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_movie_genres_genre FOREIGN KEY (genre_id)
        REFERENCES genres (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT uq_movie_genres_pair UNIQUE (movie_id, genre_id)
);

CREATE INDEX idx_movie_genres_genre ON movie_genres (genre_id, movie_id);
