CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE cinemas (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_cinemas PRIMARY KEY,
    name varchar(150) NOT NULL,
    address text NOT NULL,
    contact varchar(255),
    operating_information text,
    status varchar(30) NOT NULL,
    CONSTRAINT chk_cinemas_name CHECK (btrim(name) <> ''),
    CONSTRAINT chk_cinemas_address CHECK (btrim(address) <> ''),
    CONSTRAINT chk_cinemas_contact CHECK (contact IS NULL OR btrim(contact) <> ''),
    CONSTRAINT chk_cinemas_operating_information CHECK (operating_information IS NULL OR btrim(operating_information) <> ''),
    CONSTRAINT chk_cinemas_status CHECK (status IN ('ACTIVE','TEMPORARILY_CLOSED','INACTIVE'))
);

CREATE TABLE halls (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_halls PRIMARY KEY,
    cinema_id bigint NOT NULL,
    name varchar(100) NOT NULL,
    capacity integer NOT NULL,
    type varchar(50) NOT NULL,
    status varchar(30) NOT NULL,
    CONSTRAINT fk_halls_cinema FOREIGN KEY (cinema_id) REFERENCES cinemas(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT chk_halls_name CHECK (btrim(name) <> ''),
    CONSTRAINT chk_halls_capacity CHECK (capacity > 0),
    CONSTRAINT chk_halls_type CHECK (btrim(type) <> ''),
    CONSTRAINT chk_halls_status CHECK (status IN ('ACTIVE','MAINTENANCE','INACTIVE'))
);

CREATE TABLE showtimes (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_showtimes PRIMARY KEY,
    movie_id bigint NOT NULL,
    hall_id bigint NOT NULL,
    start_time timestamp(6) with time zone NOT NULL,
    end_time timestamp(6) with time zone NOT NULL,
    occupied_until timestamp(6) with time zone NOT NULL,
    base_price numeric(19,4) NOT NULL,
    status varchar(30) NOT NULL,
    booking_cut_off timestamp(6) with time zone NOT NULL,
    CONSTRAINT fk_showtimes_movie FOREIGN KEY (movie_id) REFERENCES movies(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_showtimes_hall FOREIGN KEY (hall_id) REFERENCES halls(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT uq_showtimes_id_hall UNIQUE (id,hall_id),
    CONSTRAINT chk_showtimes_finite_times CHECK (isfinite(start_time) AND isfinite(end_time) AND isfinite(occupied_until) AND isfinite(booking_cut_off)),
    CONSTRAINT chk_showtimes_interval CHECK (end_time > start_time AND occupied_until >= end_time AND booking_cut_off <= start_time),
    CONSTRAINT chk_showtimes_base_price CHECK (base_price >= 0 AND base_price < 1000000000000000),
    CONSTRAINT chk_showtimes_status CHECK (status IN ('DRAFT','SCHEDULED','OPEN_FOR_BOOKING','STARTED','ENDED','CANCELLED')),
    CONSTRAINT ex_showtimes_hall_occupancy EXCLUDE USING gist
        (hall_id WITH =, tstzrange(start_time,occupied_until,'[)') WITH &&)
        WHERE (status <> 'CANCELLED')
);

CREATE INDEX idx_halls_cinema ON halls(cinema_id);
CREATE INDEX idx_showtimes_movie_start ON showtimes(movie_id,start_time);
CREATE INDEX idx_showtimes_hall_start ON showtimes(hall_id,start_time);
