-- Unattached Hold stage. Booking linkage/CONSUMED must be enabled by a future
-- migration together with Booking FKs, sold-marker checks and aggregate guards.
DO $roles$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='smart_cinema_hold_owner') THEN
        CREATE ROLE smart_cinema_hold_owner NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname='smart_cinema_hold_runtime') THEN
        CREATE ROLE smart_cinema_hold_runtime NOLOGIN;
    END IF;
END $roles$;

CREATE TABLE seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_seats PRIMARY KEY,
    hall_id bigint NOT NULL,
    row varchar(20) NOT NULL,
    number varchar(20) NOT NULL,
    seat_type varchar(20) NOT NULL,
    physical_status varchar(20) NOT NULL,
    CONSTRAINT fk_seats_hall FOREIGN KEY (hall_id) REFERENCES halls(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT uq_seats_location UNIQUE (hall_id,row,number),
    CONSTRAINT uq_seats_id_hall UNIQUE (id,hall_id),
    CONSTRAINT chk_seats_row CHECK (btrim(row) <> ''),
    CONSTRAINT chk_seats_number CHECK (btrim(number) <> ''),
    CONSTRAINT chk_seats_type CHECK (seat_type IN ('STANDARD','VIP','COUPLE')),
    CONSTRAINT chk_seats_physical_status CHECK (physical_status IN ('ACTIVE','MAINTENANCE','INACTIVE'))
);

CREATE TABLE showtime_seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_showtime_seats PRIMARY KEY,
    showtime_id bigint NOT NULL,
    seat_id bigint NOT NULL,
    hall_id bigint NOT NULL,
    is_sellable boolean NOT NULL,
    CONSTRAINT uq_showtime_seats_pair UNIQUE (showtime_id,seat_id),
    CONSTRAINT fk_showtime_seats_showtime_hall FOREIGN KEY (showtime_id,hall_id)
        REFERENCES showtimes(id,hall_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_showtime_seats_seat_hall FOREIGN KEY (seat_id,hall_id)
        REFERENCES seats(id,hall_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE seat_holds (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_seat_holds PRIMARY KEY,
    showtime_id bigint NOT NULL,
    seat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    booking_id bigint,
    created_at timestamp(6) with time zone NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamp(6) with time zone NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT fk_seat_holds_pair FOREIGN KEY (showtime_id,seat_id)
        REFERENCES showtime_seats(showtime_id,seat_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_seat_holds_user FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT chk_seat_holds_times CHECK (isfinite(created_at) AND isfinite(expires_at) AND expires_at > created_at),
    CONSTRAINT chk_seat_holds_status CHECK (status IN ('ACTIVE','RELEASED','EXPIRED','CONSUMED')),
    CONSTRAINT chk_seat_holds_consumed_booking CHECK (status <> 'CONSUMED' OR booking_id IS NOT NULL),
    CONSTRAINT chk_seat_holds_unattached_stage CHECK (booking_id IS NULL AND status <> 'CONSUMED')
);

CREATE UNIQUE INDEX uq_seat_holds_active_pair ON seat_holds(showtime_id,seat_id) WHERE status='ACTIVE';
CREATE INDEX idx_showtime_seats_seat ON showtime_seats(seat_id,showtime_id);
CREATE INDEX idx_seat_holds_user ON seat_holds(user_id,created_at);
CREATE INDEX idx_seat_holds_pair_history ON seat_holds(showtime_id,seat_id,created_at);
CREATE INDEX idx_seat_holds_expiry ON seat_holds(expires_at,id) WHERE status='ACTIVE';

-- Schema-qualified bodies work in both the deployment schema and isolated upgrade
-- test schemas. SECURITY DEFINER never resolves an object through caller search_path.
DO $migration$
DECLARE
    target_schema text := current_schema();
    ddl text := $definitions$
CREATE FUNCTION app.guard_seat_hold() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF current_user <> 'smart_cinema_hold_owner' OR TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Protected Hold mutation';
    END IF;
    IF TG_OP='UPDATE' THEN
        IF (NEW.id,NEW.showtime_id,NEW.seat_id,NEW.user_id,NEW.booking_id,NEW.created_at,NEW.expires_at)
            IS DISTINCT FROM (OLD.id,OLD.showtime_id,OLD.seat_id,OLD.user_id,OLD.booking_id,OLD.created_at,OLD.expires_at)
            OR OLD.status <> 'ACTIVE' OR NEW.status NOT IN ('EXPIRED','RELEASED') THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Immutable Hold history';
        END IF;
        IF NEW.status='EXPIRED' AND OLD.expires_at > clock_timestamp() THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Hold is not expired';
        END IF;
    ELSE
        IF NEW.status <> 'ACTIVE' OR NEW.booking_id IS NOT NULL
            OR NEW.expires_at <= clock_timestamp() OR NOT EXISTS (
                SELECT 1 FROM app.showtime_seats ss JOIN app.seats seat ON seat.id=ss.seat_id
                JOIN app.showtimes s ON s.id=ss.showtime_id JOIN app.halls h ON h.id=s.hall_id
                JOIN app.cinemas c ON c.id=h.cinema_id JOIN app.movies m ON m.id=s.movie_id
                JOIN app.users u ON u.id=NEW.user_id
                WHERE ss.showtime_id=NEW.showtime_id AND ss.seat_id=NEW.seat_id AND ss.is_sellable
                AND seat.physical_status='ACTIVE' AND u.role='CUSTOMER' AND u.status='ACTIVE'
                AND m.status='PUBLISHED' AND c.status='ACTIVE' AND h.status='ACTIVE'
                AND s.status='OPEN_FOR_BOOKING' AND s.start_time > clock_timestamp()
                AND s.booking_cut_off > clock_timestamp() AND NEW.expires_at <= s.booking_cut_off) THEN
            RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Seat selection unavailable';
        END IF;
    END IF;
    RETURN NEW;
END $body$;

CREATE TRIGGER trg_seat_holds_guard BEFORE INSERT OR UPDATE OR DELETE ON app.seat_holds
FOR EACH ROW EXECUTE FUNCTION app.guard_seat_hold();

CREATE FUNCTION app.guard_seat_configuration() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF current_user <> 'smart_cinema_hold_owner' THEN
        RAISE EXCEPTION USING ERRCODE='42501', MESSAGE='Protected Seat configuration';
    END IF;
    -- Configuration is initialized through the deployment-only routines below.
    -- This slice has no editing/deletion path; future guarded administration is separate.
    IF TG_OP <> 'INSERT' THEN
        RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Seat configuration is immutable in this slice';
    END IF;
    RETURN NEW;
END $body$;
CREATE TRIGGER trg_seats_guard BEFORE INSERT OR UPDATE OR DELETE ON app.seats
FOR EACH ROW EXECUTE FUNCTION app.guard_seat_configuration();
CREATE TRIGGER trg_showtime_seats_guard BEFORE INSERT OR UPDATE OR DELETE ON app.showtime_seats
FOR EACH ROW EXECUTE FUNCTION app.guard_seat_configuration();

-- Internal lock helper. Identity discovery does not authorize; re-read after locks.
CREATE FUNCTION app.lock_hold_context(p_showtime bigint, p_user bigint) RETURNS bigint
LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_hall bigint; v_cinema bigint; v_movie bigint;
BEGIN
    IF p_user IS NOT NULL THEN
        PERFORM id FROM app.users WHERE id=p_user AND role='CUSTOMER' AND status='ACTIVE' FOR SHARE;
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0004', MESSAGE='Customer access unavailable'; END IF;
    END IF;
    SELECT s.hall_id,h.cinema_id,s.movie_id INTO v_hall,v_cinema,v_movie
        FROM app.showtimes s JOIN app.halls h ON h.id=s.hall_id WHERE s.id=p_showtime;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Showtime unavailable'; END IF;
    PERFORM id FROM app.cinemas WHERE id=v_cinema FOR SHARE;
    PERFORM id FROM app.halls WHERE id=v_hall FOR SHARE;
    PERFORM id FROM app.showtimes WHERE id=p_showtime FOR UPDATE;
    IF NOT EXISTS (SELECT 1 FROM app.showtimes s JOIN app.halls h ON h.id=s.hall_id
        WHERE s.id=p_showtime AND s.hall_id=v_hall AND h.cinema_id=v_cinema AND s.movie_id=v_movie) THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Showtime changed; reload';
    END IF;
    -- Publication is part of eligibility too; catalog-only writers take no later locks.
    PERFORM id FROM app.movies WHERE id=v_movie FOR SHARE;
    RETURN v_hall;
END $body$;

CREATE FUNCTION app.acquire_seat_holds(p_showtime bigint, p_user bigint, p_seats bigint[], p_ttl interval)
RETURNS SETOF app.seat_holds LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_hall bigint; v_now timestamptz; v_expiry timestamptz; v_existing_expiry timestamptz;
BEGIN
    IF p_seats IS NULL OR cardinality(p_seats)=0 OR p_ttl IS NULL OR p_ttl <= interval '0 seconds'
        OR EXISTS(SELECT 1 FROM unnest(p_seats) id WHERE id IS NULL OR id<=0)
        OR (SELECT count(DISTINCT id) FROM unnest(p_seats) id) <> cardinality(p_seats) THEN
        RAISE EXCEPTION USING ERRCODE='P0001', MESSAGE='Invalid Seat selection';
    END IF;
    v_hall := app.lock_hold_context(p_showtime,p_user);
    PERFORM id FROM app.seats WHERE id=ANY(p_seats) ORDER BY id FOR SHARE;
    PERFORM id FROM app.showtime_seats WHERE showtime_id=p_showtime AND seat_id=ANY(p_seats)
        ORDER BY seat_id FOR UPDATE;
    v_now := clock_timestamp();
    SELECT least(s.start_time,s.booking_cut_off,v_now+p_ttl) INTO v_expiry
        FROM app.showtimes s JOIN app.halls h ON h.id=s.hall_id JOIN app.cinemas c ON c.id=h.cinema_id
        JOIN app.movies m ON m.id=s.movie_id WHERE s.id=p_showtime AND m.status='PUBLISHED'
        AND c.status='ACTIVE' AND h.status='ACTIVE' AND s.status='OPEN_FOR_BOOKING'
        AND s.start_time>v_now AND s.booking_cut_off>v_now;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Showtime unavailable'; END IF;
    IF (SELECT count(*) FROM app.showtime_seats ss JOIN app.seats s ON s.id=ss.seat_id
        WHERE ss.showtime_id=p_showtime AND ss.seat_id=ANY(p_seats) AND ss.hall_id=v_hall
        AND ss.is_sellable AND s.physical_status='ACTIVE') <> cardinality(p_seats) THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Seat selection unavailable';
    END IF;
    PERFORM id FROM app.seat_holds WHERE showtime_id=p_showtime AND seat_id=ANY(p_seats)
        AND status='ACTIVE' ORDER BY id FOR UPDATE;
    v_now := clock_timestamp();
    UPDATE app.seat_holds SET status='EXPIRED' WHERE showtime_id=p_showtime AND seat_id=ANY(p_seats)
        AND status='ACTIVE' AND expires_at<=v_now;
    IF EXISTS (SELECT 1 FROM app.seat_holds WHERE showtime_id=p_showtime AND seat_id=ANY(p_seats)
        AND status='ACTIVE' AND (user_id<>p_user OR booking_id IS NOT NULL)) THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Seat selection unavailable';
    END IF;
    SELECT min(expires_at) INTO v_existing_expiry FROM app.seat_holds
        WHERE showtime_id=p_showtime AND seat_id=ANY(p_seats) AND status='ACTIVE';
    v_expiry := least(v_expiry,v_existing_expiry);
    IF v_expiry <= clock_timestamp() THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Seat selection expired; reload';
    END IF;
    INSERT INTO app.seat_holds(showtime_id,seat_id,user_id,created_at,expires_at,status)
        SELECT p_showtime,selected.id,p_user,v_now,v_expiry,'ACTIVE' FROM unnest(p_seats) selected(id)
        WHERE NOT EXISTS (SELECT 1 FROM app.seat_holds sh WHERE sh.showtime_id=p_showtime
            AND sh.seat_id=selected.id AND sh.status='ACTIVE') ORDER BY selected.id;
    IF v_expiry <= clock_timestamp() THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Seat selection expired; reload';
    END IF;
    RETURN QUERY SELECT * FROM app.seat_holds WHERE showtime_id=p_showtime
        AND seat_id=ANY(p_seats) AND user_id=p_user AND status='ACTIVE' ORDER BY seat_id;
END $body$;

CREATE FUNCTION app.release_seat_hold(p_showtime bigint,p_user bigint,p_hold bigint) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_seat bigint; v_hold app.seat_holds%ROWTYPE; v_now timestamptz;
BEGIN
    PERFORM app.lock_hold_context(p_showtime,p_user);
    SELECT seat_id INTO v_seat FROM app.seat_holds WHERE id=p_hold AND showtime_id=p_showtime AND user_id=p_user;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Hold unavailable'; END IF;
    PERFORM id FROM app.seats WHERE id=v_seat FOR SHARE;
    PERFORM id FROM app.showtime_seats WHERE showtime_id=p_showtime AND seat_id=v_seat FOR UPDATE;
    SELECT * INTO v_hold FROM app.seat_holds WHERE id=p_hold AND showtime_id=p_showtime AND user_id=p_user FOR UPDATE;
    IF v_hold.booking_id IS NOT NULL THEN RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Attached Hold cannot be released'; END IF;
    IF v_hold.status='ACTIVE' THEN
        v_now:=clock_timestamp();
        UPDATE app.seat_holds SET status=CASE WHEN expires_at<=v_now THEN 'EXPIRED' ELSE 'RELEASED' END WHERE id=p_hold;
    END IF;
END $body$;

CREATE FUNCTION app.expire_seat_holds(p_showtime bigint) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_hall bigint; v_count integer;
BEGIN
    v_hall := app.lock_hold_context(p_showtime,NULL);
    PERFORM id FROM app.seats WHERE hall_id=v_hall ORDER BY id FOR SHARE;
    PERFORM id FROM app.showtime_seats WHERE showtime_id=p_showtime ORDER BY seat_id FOR UPDATE;
    PERFORM id FROM app.seat_holds WHERE showtime_id=p_showtime AND status='ACTIVE' ORDER BY id FOR UPDATE;
    UPDATE app.seat_holds SET status='EXPIRED' WHERE showtime_id=p_showtime
        AND status='ACTIVE' AND booking_id IS NULL AND expires_at<=clock_timestamp();
    GET DIAGNOSTICS v_count=ROW_COUNT;
    RETURN v_count;
END $body$;

-- Deployment-only initial configuration: no HTTP/admin CRUD added.
CREATE FUNCTION app.initialize_hall_seats(p_hall bigint,p_units jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_cinema bigint; v_capacity integer;
BEGIN
    SELECT cinema_id INTO v_cinema FROM app.halls WHERE id=p_hall;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Hall unavailable'; END IF;
    PERFORM id FROM app.cinemas WHERE id=v_cinema FOR SHARE;
    SELECT capacity INTO v_capacity FROM app.halls WHERE id=p_hall AND cinema_id=v_cinema FOR UPDATE;
    IF NOT FOUND OR EXISTS(SELECT 1 FROM app.seats WHERE hall_id=p_hall) THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Hall layout already initialized or changed';
    END IF;
    IF p_units IS NULL OR jsonb_typeof(p_units)<>'array' OR jsonb_array_length(p_units)=0 THEN
        RAISE EXCEPTION USING ERRCODE='P0001', MESSAGE='Initial Seat layout required';
    END IF;
    INSERT INTO app.seats(hall_id,row,number,seat_type,physical_status)
        SELECT p_hall,btrim(unit->>'row'),btrim(unit->>'number'),unit->>'type',unit->>'physicalStatus'
        FROM jsonb_array_elements(p_units) unit;
    IF (SELECT sum(CASE WHEN seat_type='COUPLE' THEN 2 ELSE 1 END) FROM app.seats WHERE hall_id=p_hall)<>v_capacity THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Layout guest capacity does not match Hall';
    END IF;
END $body$;

CREATE FUNCTION app.initialize_showtime_seats(p_showtime bigint,p_sellable bigint[]) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_hall bigint; v_cinema bigint;
BEGIN
    SELECT s.hall_id,h.cinema_id INTO v_hall,v_cinema FROM app.showtimes s JOIN app.halls h ON h.id=s.hall_id WHERE s.id=p_showtime;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002', MESSAGE='Showtime unavailable'; END IF;
    PERFORM id FROM app.cinemas WHERE id=v_cinema FOR SHARE;
    PERFORM id FROM app.halls WHERE id=v_hall FOR UPDATE;
    PERFORM id FROM app.showtimes WHERE id=p_showtime AND hall_id=v_hall FOR UPDATE;
    IF NOT FOUND OR EXISTS(SELECT 1 FROM app.showtime_seats WHERE showtime_id=p_showtime)
        OR NOT EXISTS(SELECT 1 FROM app.seats WHERE hall_id=v_hall) THEN
        RAISE EXCEPTION USING ERRCODE='P0003', MESSAGE='Showtime layout unavailable or already initialized';
    END IF;
    IF p_sellable IS NULL OR (SELECT count(DISTINCT id) FROM unnest(p_sellable) id)<>cardinality(p_sellable)
        OR EXISTS(SELECT 1 FROM unnest(p_sellable) selected(id) WHERE NOT EXISTS
            (SELECT 1 FROM app.seats WHERE id=selected.id AND hall_id=v_hall)) THEN
        RAISE EXCEPTION USING ERRCODE='P0001', MESSAGE='Invalid sellable Seat identities';
    END IF;
    INSERT INTO app.showtime_seats(showtime_id,seat_id,hall_id,is_sellable)
        SELECT p_showtime,id,v_hall,id=ANY(p_sellable) FROM app.seats WHERE hall_id=v_hall ORDER BY id;
END $body$;

CREATE FUNCTION app.guard_hold_parent() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF TG_TABLE_NAME='showtimes' THEN
        IF (NEW.movie_id,NEW.hall_id,NEW.start_time,NEW.end_time,NEW.booking_cut_off)
            IS DISTINCT FROM (OLD.movie_id,OLD.hall_id,OLD.start_time,OLD.end_time,OLD.booking_cut_off)
            AND EXISTS(SELECT 1 FROM app.seat_holds WHERE showtime_id=OLD.id) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Hold history prevents screening identity/time changes';
        END IF;
    ELSE
        IF (NEW.cinema_id,NEW.capacity) IS DISTINCT FROM (OLD.cinema_id,OLD.capacity)
            AND EXISTS(SELECT 1 FROM app.seats WHERE hall_id=OLD.id) THEN
            RAISE EXCEPTION USING ERRCODE='23514', MESSAGE='Initialized layout prevents Hall membership/capacity changes';
        END IF;
    END IF;
    RETURN NEW;
END $body$;
CREATE TRIGGER trg_showtimes_hold_history BEFORE UPDATE ON app.showtimes FOR EACH ROW EXECUTE FUNCTION app.guard_hold_parent();
CREATE TRIGGER trg_halls_seat_history BEFORE UPDATE ON app.halls FOR EACH ROW EXECUTE FUNCTION app.guard_hold_parent();

REVOKE ALL ON FUNCTION app.guard_seat_hold(), app.guard_seat_configuration(), app.guard_hold_parent(), app.lock_hold_context(bigint,bigint),
    app.acquire_seat_holds(bigint,bigint,bigint[],interval), app.release_seat_hold(bigint,bigint,bigint),
    app.expire_seat_holds(bigint), app.initialize_hall_seats(bigint,jsonb), app.initialize_showtime_seats(bigint,bigint[]) FROM PUBLIC;
ALTER FUNCTION app.guard_seat_hold() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.guard_seat_configuration() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.guard_hold_parent() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.lock_hold_context(bigint,bigint) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.acquire_seat_holds(bigint,bigint,bigint[],interval) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.release_seat_hold(bigint,bigint,bigint) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.expire_seat_holds(bigint) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.initialize_hall_seats(bigint,jsonb) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.initialize_showtime_seats(bigint,bigint[]) OWNER TO smart_cinema_hold_owner;
ALTER TABLE app.seats OWNER TO smart_cinema_hold_owner;
ALTER TABLE app.showtime_seats OWNER TO smart_cinema_hold_owner;
ALTER TABLE app.seat_holds OWNER TO smart_cinema_hold_owner;
GRANT SELECT,UPDATE ON app.users,app.cinemas,app.halls,app.showtimes,app.movies TO smart_cinema_hold_owner;
REVOKE ALL ON app.seats,app.showtime_seats,app.seat_holds FROM PUBLIC;
GRANT SELECT ON app.seats,app.showtime_seats,app.seat_holds,app.users,app.cinemas,app.halls,app.showtimes,app.movies TO smart_cinema_hold_runtime;
GRANT EXECUTE ON FUNCTION app.acquire_seat_holds(bigint,bigint,bigint[],interval),
    app.release_seat_hold(bigint,bigint,bigint),app.expire_seat_holds(bigint) TO smart_cinema_hold_runtime;
$definitions$;
BEGIN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO smart_cinema_hold_owner,smart_cinema_hold_runtime',target_schema);
    EXECUTE replace(ddl,'app.',format('%I.',target_schema));
END $migration$;
