-- Pre-Payment aggregate. No sale, consumption, freeze, Ticket or QR writer is enabled.
CREATE TABLE bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_bookings PRIMARY KEY,
    booking_code varchar(40) NOT NULL CONSTRAINT uq_bookings_code UNIQUE,
    booking_qr_token varchar(128) CONSTRAINT uq_bookings_qr UNIQUE,
    customer_id bigint NOT NULL CONSTRAINT fk_bookings_customer REFERENCES users(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    showtime_id bigint NOT NULL CONSTRAINT fk_bookings_showtime REFERENCES showtimes(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    promotion_id bigint,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    seat_amount numeric(19,4) NOT NULL,
    concession_amount numeric(19,4) NOT NULL,
    subtotal numeric(19,4) NOT NULL,
    discount numeric(19,4) NOT NULL,
    final_amount numeric(19,4) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamp(6) with time zone NOT NULL,
    payment_started_at timestamp(6) with time zone,
    paid_at timestamp(6) with time zone,
    CONSTRAINT uq_bookings_id_showtime UNIQUE(id,showtime_id),
    CONSTRAINT uq_bookings_id_showtime_customer UNIQUE(id,showtime_id,customer_id),
    CONSTRAINT chk_bookings_code CHECK(btrim(booking_code)<>''),
    CONSTRAINT chk_bookings_qr CHECK(booking_qr_token IS NULL OR btrim(booking_qr_token)<>''),
    CONSTRAINT chk_bookings_status CHECK(status IN ('PENDING','PAID','EXPIRED','CANCELLED')),
    CONSTRAINT chk_bookings_times CHECK(isfinite(created_at) AND isfinite(expires_at) AND expires_at>created_at
        AND (payment_started_at IS NULL OR (isfinite(payment_started_at) AND payment_started_at>=created_at AND payment_started_at<expires_at))
        AND (paid_at IS NULL OR (isfinite(paid_at) AND paid_at>=payment_started_at AND paid_at<expires_at))),
    CONSTRAINT chk_bookings_money CHECK(seat_amount>=0 AND seat_amount<1000000000000000
        AND concession_amount>=0 AND concession_amount<1000000000000000
        AND subtotal>=0 AND subtotal<1000000000000000 AND discount>=0 AND discount<1000000000000000
        AND final_amount>=0 AND final_amount<1000000000000000),
    CONSTRAINT chk_bookings_totals CHECK(subtotal=seat_amount+concession_amount AND discount<=subtotal AND final_amount=subtotal-discount),
    CONSTRAINT chk_bookings_promotion CHECK(promotion_id IS NOT NULL OR discount=0),
    CONSTRAINT chk_bookings_paid CHECK((status='PAID' AND paid_at IS NOT NULL AND payment_started_at IS NOT NULL AND booking_qr_token IS NOT NULL)
        OR (status<>'PAID' AND paid_at IS NULL AND booking_qr_token IS NULL)),
    CONSTRAINT chk_bookings_pre_payment_stage CHECK(status<>'PAID' AND payment_started_at IS NULL
        AND promotion_id IS NULL AND concession_amount=0 AND discount=0)
);
CREATE TABLE booking_seats (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_booking_seats PRIMARY KEY,
    booking_id bigint NOT NULL,
    showtime_id bigint NOT NULL,
    seat_id bigint NOT NULL,
    seat_type_snapshot varchar(20) NOT NULL,
    unit_price_snapshot numeric(19,4) NOT NULL,
    final_price numeric(19,4) NOT NULL,
    sold_at timestamp(6) with time zone,
    CONSTRAINT fk_booking_seats_pair FOREIGN KEY(showtime_id,seat_id) REFERENCES showtime_seats(showtime_id,seat_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_booking_seats_booking_showtime FOREIGN KEY(booking_id,showtime_id) REFERENCES bookings(id,showtime_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT uq_booking_seats_booking_seat UNIQUE(booking_id,seat_id),
    CONSTRAINT uq_booking_seats_booking_pair UNIQUE(booking_id,showtime_id,seat_id),
    CONSTRAINT chk_booking_seats_type CHECK(seat_type_snapshot IN ('STANDARD','VIP','COUPLE')),
    CONSTRAINT chk_booking_seats_money CHECK(unit_price_snapshot>=0 AND unit_price_snapshot<1000000000000000
        AND final_price>=0 AND final_price<1000000000000000),
    CONSTRAINT chk_booking_seats_sold_time CHECK(sold_at IS NULL OR isfinite(sold_at)),
    CONSTRAINT chk_booking_seats_pre_payment_stage CHECK(sold_at IS NULL)
);
ALTER TABLE seat_holds DROP CONSTRAINT chk_seat_holds_unattached_stage;
ALTER TABLE seat_holds ADD CONSTRAINT chk_seat_holds_pre_payment_stage CHECK(status<>'CONSUMED');
ALTER TABLE seat_holds ADD CONSTRAINT uq_seat_holds_booking_seat UNIQUE(booking_id,seat_id);
ALTER TABLE seat_holds ADD CONSTRAINT fk_seat_holds_booking_owner FOREIGN KEY(booking_id,showtime_id,user_id)
    REFERENCES bookings(id,showtime_id,customer_id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE seat_holds ADD CONSTRAINT fk_seat_holds_booking_line FOREIGN KEY(booking_id,showtime_id,seat_id)
    REFERENCES booking_seats(booking_id,showtime_id,seat_id) ON UPDATE NO ACTION ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED;
CREATE UNIQUE INDEX uq_booking_seats_sold_pair ON booking_seats(showtime_id,seat_id) WHERE sold_at IS NOT NULL;
CREATE INDEX idx_bookings_customer_created ON bookings(customer_id,created_at DESC,id);
CREATE INDEX idx_bookings_showtime ON bookings(showtime_id,status);
CREATE INDEX idx_bookings_promotion ON bookings(promotion_id,status);
CREATE INDEX idx_bookings_pending_expiry ON bookings(expires_at,id) WHERE status='PENDING';
CREATE INDEX idx_booking_seats_pair_history ON booking_seats(showtime_id,seat_id,booking_id);

DO $migration$
DECLARE target_schema text:=current_schema(); ddl text:=$definitions$
CREATE FUNCTION app.guard_booking() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF current_user<>'smart_cinema_hold_owner' OR TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Protected Booking mutation';
    END IF;
    IF TG_OP='INSERT' THEN
        IF NEW.status<>'PENDING' OR NEW.expires_at<=clock_timestamp() THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid initial Booking';
        END IF;
    ELSE
        IF (to_jsonb(NEW)-'status') IS DISTINCT FROM (to_jsonb(OLD)-'status')
            OR OLD.status<>'PENDING' OR NEW.status NOT IN ('CANCELLED','EXPIRED')
            OR (NEW.status='EXPIRED' AND NEW.expires_at>clock_timestamp()) THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Immutable Booking history';
        END IF;
    END IF;
    RETURN NEW;
END $body$;
CREATE TRIGGER trg_bookings_guard BEFORE INSERT OR UPDATE OR DELETE ON app.bookings FOR EACH ROW EXECUTE FUNCTION app.guard_booking();

CREATE FUNCTION app.guard_booking_seat() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF current_user<>'smart_cinema_hold_owner' OR TG_OP<>'INSERT' THEN
        RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Immutable Booking Seat';
    END IF;
    IF NEW.sold_at IS NOT NULL OR NOT EXISTS (
        SELECT 1 FROM app.bookings b JOIN app.showtimes s ON s.id=b.showtime_id
        JOIN app.seat_holds h ON h.showtime_id=b.showtime_id AND h.user_id=b.customer_id AND h.seat_id=NEW.seat_id
        JOIN app.seats seat ON seat.id=h.seat_id
        -- Pending headers cannot be updated in this slice: xmin proves insertion in this transaction.
        -- This also prevents adding zero-price lines to a previously committed Booking.
        WHERE b.id=NEW.booking_id AND b.xmin=pg_current_xact_id()::xid
        AND b.status='PENDING' AND b.expires_at>clock_timestamp()
        AND h.booking_id IS NULL AND h.status='ACTIVE' AND h.expires_at>clock_timestamp()
        AND NEW.seat_type_snapshot=seat.seat_type AND NEW.unit_price_snapshot=s.base_price
        AND NEW.final_price=NEW.unit_price_snapshot) THEN
        RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid Booking Seat origin or snapshot';
    END IF;
    RETURN NEW;
END $body$;
CREATE TRIGGER trg_booking_seats_guard BEFORE INSERT OR UPDATE OR DELETE ON app.booking_seats FOR EACH ROW EXECUTE FUNCTION app.guard_booking_seat();

CREATE FUNCTION app.assert_booking() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_id bigint; b app.bookings%ROWTYPE;
BEGIN
    IF TG_TABLE_NAME='bookings' THEN v_id:=coalesce(NEW.id,OLD.id); ELSE v_id:=coalesce(NEW.booking_id,OLD.booking_id); END IF;
    IF v_id IS NULL THEN RETURN NULL; END IF;
    SELECT * INTO b FROM app.bookings WHERE id=v_id;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Missing Booking aggregate'; END IF;
    IF NOT EXISTS(SELECT 1 FROM app.booking_seats WHERE booking_id=v_id)
        OR b.seat_amount<>(SELECT coalesce(sum(final_price),0) FROM app.booking_seats WHERE booking_id=v_id)
        OR b.expires_at>(SELECT booking_cut_off FROM app.showtimes WHERE id=b.showtime_id)
        OR EXISTS(SELECT 1 FROM app.booking_seats bs LEFT JOIN app.seat_holds h
            ON h.booking_id=bs.booking_id AND h.seat_id=bs.seat_id AND h.showtime_id=bs.showtime_id
            WHERE bs.booking_id=v_id AND (h.id IS NULL OR h.user_id<>b.customer_id OR b.expires_at>h.expires_at
                OR (b.status='PENDING' AND h.status<>'ACTIVE')
                OR (b.status IN ('EXPIRED','CANCELLED') AND h.status NOT IN ('EXPIRED','RELEASED'))
                OR bs.sold_at IS NOT NULL)) THEN
        RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Incomplete Booking aggregate';
    END IF;
    RETURN NULL;
END $body$;
CREATE CONSTRAINT TRIGGER ct_booking_composition AFTER INSERT OR UPDATE OR DELETE ON app.bookings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_booking();
CREATE CONSTRAINT TRIGGER ct_booking_seat_composition AFTER INSERT OR UPDATE OR DELETE ON app.booking_seats DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_booking();
CREATE CONSTRAINT TRIGGER ct_booking_hold_composition AFTER INSERT OR UPDATE OR DELETE ON app.seat_holds DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_booking();

-- Caller owns the Showtime gate. Lock the full resource set before any Booking/Hold mutation.
-- Conservative MVP scope: all pairs for this Showtime, avoiding aggregate expansion inversions.
CREATE FUNCTION app.lock_booking_resources(p_showtime bigint) RETURNS void LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    PERFORM seat.id FROM app.seats seat JOIN app.showtimes s ON s.hall_id=seat.hall_id WHERE s.id=p_showtime ORDER BY seat.id FOR SHARE OF seat;
    PERFORM id FROM app.showtime_seats WHERE showtime_id=p_showtime ORDER BY seat_id FOR UPDATE;
    PERFORM id FROM app.bookings WHERE showtime_id=p_showtime ORDER BY id FOR UPDATE;
    PERFORM id FROM app.seat_holds WHERE showtime_id=p_showtime ORDER BY id FOR UPDATE;
END $body$;
CREATE FUNCTION app.expire_booking_aggregates(p_showtime bigint) RETURNS integer LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_count integer; v_now timestamptz:=clock_timestamp();
BEGIN
    UPDATE app.bookings SET status='EXPIRED' WHERE showtime_id=p_showtime AND status='PENDING' AND expires_at<=v_now;
    UPDATE app.seat_holds h SET status='EXPIRED' WHERE h.showtime_id=p_showtime AND h.status='ACTIVE'
        AND (h.expires_at<=v_now OR EXISTS(SELECT 1 FROM app.bookings b WHERE b.id=h.booking_id AND b.status='EXPIRED'));
    GET DIAGNOSTICS v_count=ROW_COUNT;
    RETURN v_count;
END $body$;

CREATE FUNCTION app.create_booking(p_showtime bigint,p_user bigint,p_holds bigint[]) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_now timestamptz; v_expiry timestamptz; v_price numeric; v_id bigint; v_existing bigint;
BEGIN
    IF p_holds IS NULL OR cardinality(p_holds)=0 OR EXISTS(SELECT 1 FROM unnest(p_holds) id WHERE id IS NULL OR id<=0)
        OR (SELECT count(DISTINCT id) FROM unnest(p_holds) id)<>cardinality(p_holds) THEN
        RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='Invalid Hold selection';
    END IF;
    PERFORM app.lock_hold_context(p_showtime,p_user);
    PERFORM app.lock_booking_resources(p_showtime);
    PERFORM app.expire_booking_aggregates(p_showtime);
    v_now:=clock_timestamp();
    SELECT s.base_price,least(s.start_time,s.booking_cut_off) INTO v_price,v_expiry
        FROM app.showtimes s JOIN app.halls h ON h.id=s.hall_id JOIN app.cinemas c ON c.id=h.cinema_id JOIN app.movies m ON m.id=s.movie_id
        WHERE s.id=p_showtime AND s.status='OPEN_FOR_BOOKING' AND s.start_time>v_now AND s.booking_cut_off>v_now
        AND h.status='ACTIVE' AND c.status='ACTIVE' AND m.status='PUBLISHED';
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Showtime unavailable'; END IF;
    IF (SELECT count(*) FROM app.seat_holds h JOIN app.showtime_seats ss ON ss.showtime_id=h.showtime_id AND ss.seat_id=h.seat_id
        JOIN app.seats seat ON seat.id=h.seat_id WHERE h.id=ANY(p_holds) AND h.showtime_id=p_showtime AND h.user_id=p_user
        AND h.status='ACTIVE' AND h.expires_at>v_now AND ss.is_sellable AND seat.physical_status='ACTIVE'
        AND NOT EXISTS(SELECT 1 FROM app.booking_seats bs WHERE bs.showtime_id=p_showtime AND bs.seat_id=h.seat_id AND bs.sold_at IS NOT NULL))<>cardinality(p_holds) THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Hold selection unavailable';
    END IF;
    SELECT min(booking_id) INTO v_existing FROM app.seat_holds WHERE id=ANY(p_holds);
    IF v_existing IS NOT NULL THEN
        IF EXISTS(SELECT 1 FROM app.seat_holds WHERE id=ANY(p_holds) AND booking_id IS DISTINCT FROM v_existing)
            OR (SELECT count(*) FROM app.seat_holds WHERE booking_id=v_existing)<>cardinality(p_holds)
            OR NOT EXISTS(SELECT 1 FROM app.bookings WHERE id=v_existing AND customer_id=p_user AND status='PENDING' AND expires_at>clock_timestamp()) THEN
            RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Hold already attached';
        END IF;
        RETURN v_existing;
    END IF;
    SELECT least(v_expiry,min(expires_at)) INTO v_expiry FROM app.seat_holds WHERE id=ANY(p_holds);
    IF v_price*cardinality(p_holds)>=1000000000000000 THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking amount exceeds supported bounds';
    END IF;
    v_now:=clock_timestamp();
    IF v_expiry<=v_now THEN RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Hold selection expired'; END IF;
    INSERT INTO app.bookings(booking_code,customer_id,showtime_id,seat_amount,concession_amount,subtotal,discount,final_amount,created_at,expires_at)
        VALUES ('B-'||replace(gen_random_uuid()::text,'-',''),p_user,p_showtime,v_price*cardinality(p_holds),0,
            v_price*cardinality(p_holds),0,v_price*cardinality(p_holds),v_now,v_expiry) RETURNING id INTO v_id;
    INSERT INTO app.booking_seats(booking_id,showtime_id,seat_id,seat_type_snapshot,unit_price_snapshot,final_price)
        SELECT v_id,p_showtime,h.seat_id,seat.seat_type,v_price,v_price FROM app.seat_holds h JOIN app.seats seat ON seat.id=h.seat_id
        WHERE h.id=ANY(p_holds) ORDER BY h.seat_id;
    UPDATE app.seat_holds SET booking_id=v_id WHERE id=ANY(p_holds);
    IF v_expiry<=clock_timestamp() THEN RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Hold selection expired'; END IF;
    RETURN v_id;
END $body$;

CREATE FUNCTION app.cancel_booking(p_booking bigint,p_user bigint) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_showtime bigint;
BEGIN
    SELECT showtime_id INTO v_showtime FROM app.bookings WHERE id=p_booking AND customer_id=p_user;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Booking unavailable'; END IF;
    PERFORM app.lock_hold_context(v_showtime,p_user);
    PERFORM app.lock_booking_resources(v_showtime);
    PERFORM app.expire_booking_aggregates(v_showtime);
    UPDATE app.bookings SET status='CANCELLED' WHERE id=p_booking AND customer_id=p_user AND status='PENDING';
    UPDATE app.seat_holds SET status='RELEASED' WHERE booking_id=p_booking AND status='ACTIVE'
        AND EXISTS(SELECT 1 FROM app.bookings WHERE id=p_booking AND status='CANCELLED');
END $body$;
CREATE OR REPLACE FUNCTION app.expire_seat_holds(p_showtime bigint) RETURNS integer
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    PERFORM app.lock_hold_context(p_showtime,NULL);
    PERFORM app.lock_booking_resources(p_showtime);
    RETURN app.expire_booking_aggregates(p_showtime);
END $body$;

ALTER TABLE app.bookings OWNER TO smart_cinema_hold_owner;
ALTER TABLE app.booking_seats OWNER TO smart_cinema_hold_owner;
REVOKE ALL ON app.bookings,app.booking_seats FROM PUBLIC;
GRANT SELECT ON app.bookings,app.booking_seats TO smart_cinema_hold_runtime;
ALTER FUNCTION app.guard_booking() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.guard_booking_seat() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.assert_booking() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.lock_booking_resources(bigint) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.expire_booking_aggregates(bigint) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.create_booking(bigint,bigint,bigint[]) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.cancel_booking(bigint,bigint) OWNER TO smart_cinema_hold_owner;
REVOKE ALL ON FUNCTION app.guard_booking(),app.guard_booking_seat(),app.assert_booking(),app.lock_booking_resources(bigint),
    app.expire_booking_aggregates(bigint),app.create_booking(bigint,bigint,bigint[]),app.cancel_booking(bigint,bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.create_booking(bigint,bigint,bigint[]),app.cancel_booking(bigint,bigint) TO smart_cinema_hold_runtime;
$definitions$;
BEGIN
    EXECUTE replace(ddl,'app.',format('%I.',target_schema));
END $migration$;

-- Replace only the V5 guard branches that must understand permanent attachment.
-- The migration asserts each patch anchor, so drift fails migration rather than silently weakening guards.
DO $upgrade$
DECLARE ns text:=current_schema(); source text; anchor text; replacement text;
BEGIN
    source:=pg_get_functiondef(format('%I.guard_seat_hold()',ns)::regprocedure);
    anchor:='IF (NEW.id,NEW.showtime_id,NEW.seat_id,NEW.user_id,NEW.booking_id,NEW.created_at,NEW.expires_at)';
    IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected V5 guard definition'; END IF;
    source:=replace(source,anchor,'IF (NEW.id,NEW.showtime_id,NEW.seat_id,NEW.user_id,NEW.created_at,NEW.expires_at)');
    source:=replace(source,'(OLD.id,OLD.showtime_id,OLD.seat_id,OLD.user_id,OLD.booking_id,OLD.created_at,OLD.expires_at)',
        '(OLD.id,OLD.showtime_id,OLD.seat_id,OLD.user_id,OLD.created_at,OLD.expires_at)');
    source:=replace(source,'OR OLD.status <> ''ACTIVE'' OR NEW.status NOT IN (''EXPIRED'',''RELEASED'')',
        'OR OLD.status <> ''ACTIVE'' OR NEW.status NOT IN (''ACTIVE'',''EXPIRED'',''RELEASED'')');
    anchor:='IF NEW.status=''EXPIRED'' AND OLD.expires_at > clock_timestamp() THEN';
    replacement:=format($text$
        IF OLD.booking_id IS NOT NULL AND NEW.booking_id IS DISTINCT FROM OLD.booking_id THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Permanent Hold attachment';
        END IF;
        IF NEW.status='ACTIVE' AND (OLD.booking_id IS NOT NULL OR NEW.booking_id IS NULL OR OLD.expires_at<=clock_timestamp()
            OR NOT EXISTS(SELECT 1 FROM %1$I.bookings b WHERE b.id=NEW.booking_id AND b.customer_id=NEW.user_id
                AND b.showtime_id=NEW.showtime_id AND b.status='PENDING' AND b.expires_at>clock_timestamp())) THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid Hold attachment';
        END IF;
        IF NEW.status<>'ACTIVE' AND NEW.booking_id IS DISTINCT FROM OLD.booking_id THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid terminal attachment';
        END IF;
        IF OLD.booking_id IS NOT NULL AND NEW.status<>'ACTIVE' AND NOT EXISTS(
            SELECT 1 FROM %1$I.bookings b WHERE b.id=OLD.booking_id AND
                ((NEW.status='EXPIRED' AND b.status='EXPIRED') OR (NEW.status='RELEASED' AND b.status='CANCELLED'))) THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Release whole Booking only';
        END IF;
        IF NEW.status='EXPIRED' AND OLD.expires_at > clock_timestamp() AND NOT EXISTS(
            SELECT 1 FROM %1$I.bookings b WHERE b.id=OLD.booking_id AND b.status='EXPIRED') THEN
$text$,ns);
    IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected V5 expiry guard'; END IF;
    source:=replace(source,anchor,replacement);
    anchor:='IF NEW.status <> ''ACTIVE'' OR NEW.booking_id IS NOT NULL';
    source:=replace(source,anchor,format('IF EXISTS(SELECT 1 FROM %I.booking_seats bs WHERE bs.showtime_id=NEW.showtime_id AND bs.seat_id=NEW.seat_id AND bs.sold_at IS NOT NULL) OR NEW.status <> ''ACTIVE'' OR NEW.booking_id IS NOT NULL',ns));
    EXECUTE source;

    source:=pg_get_functiondef(format('%I.acquire_seat_holds(bigint,bigint,bigint[],interval)',ns)::regprocedure);
    anchor:=format('v_hall := %I.lock_hold_context(p_showtime,p_user);',ns);
    IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected V5 acquire definition'; END IF;
    source:=replace(source,anchor,anchor||format(E'\n    PERFORM %1$I.lock_booking_resources(p_showtime);\n    PERFORM %1$I.expire_booking_aggregates(p_showtime);\n    IF EXISTS(SELECT 1 FROM %1$I.booking_seats WHERE showtime_id=p_showtime AND seat_id=ANY(p_seats) AND sold_at IS NOT NULL) THEN RAISE EXCEPTION USING ERRCODE=''P0003'',MESSAGE=''Seat sold''; END IF;',ns));
    -- Aggregate expiry handled above; never retire one attached line independently.
    source:=replace(source,'AND status=''ACTIVE'' AND expires_at<=v_now;', 'AND status=''ACTIVE'' AND booking_id IS NULL AND expires_at<=v_now;');
    EXECUTE source;
END $upgrade$;
