-- Concession composition before Payment. Promotion is schema-only until policy is approved.
CREATE TABLE concession_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_concession_items PRIMARY KEY,
    name varchar(150) NOT NULL,
    description text,
    category varchar(30) NOT NULL,
    selling_price numeric(19,4) NOT NULL,
    image varchar(2048),
    status varchar(20) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamp(6) with time zone NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT chk_concession_items_name CHECK(btrim(name)<>''),
    CONSTRAINT chk_concession_items_description CHECK(description IS NULL OR btrim(description)<>''),
    CONSTRAINT chk_concession_items_image CHECK(image IS NULL OR btrim(image)<>''),
    CONSTRAINT chk_concession_items_category CHECK(category IN ('POPCORN','DRINK','COMBO')),
    CONSTRAINT chk_concession_items_status CHECK(status IN ('ACTIVE','INACTIVE')),
    CONSTRAINT chk_concession_items_price CHECK(selling_price>=0 AND selling_price<1000000000000000),
    CONSTRAINT chk_concession_items_times CHECK(isfinite(created_at) AND isfinite(updated_at) AND updated_at>=created_at)
);
CREATE TABLE booking_concessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_booking_concessions PRIMARY KEY,
    booking_id bigint NOT NULL,
    concession_item_id bigint NOT NULL,
    item_name_snapshot varchar(150) NOT NULL,
    category_snapshot varchar(30) NOT NULL,
    quantity integer NOT NULL,
    unit_price_snapshot numeric(19,4) NOT NULL,
    total_price numeric(19,4) NOT NULL,
    CONSTRAINT fk_booking_concessions_booking FOREIGN KEY(booking_id) REFERENCES bookings(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT fk_booking_concessions_item FOREIGN KEY(concession_item_id) REFERENCES concession_items(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT chk_booking_concessions_name CHECK(btrim(item_name_snapshot)<>''),
    CONSTRAINT chk_booking_concessions_category CHECK(category_snapshot IN ('POPCORN','DRINK','COMBO')),
    CONSTRAINT chk_booking_concessions_quantity CHECK(quantity>0),
    CONSTRAINT chk_booking_concessions_money CHECK(unit_price_snapshot>=0 AND unit_price_snapshot<1000000000000000
        AND total_price>=0 AND total_price<1000000000000000),
    CONSTRAINT chk_booking_concessions_total CHECK(total_price=quantity*unit_price_snapshot)
);
CREATE INDEX idx_booking_concessions_booking ON booking_concessions(booking_id);
CREATE INDEX idx_booking_concessions_item ON booking_concessions(concession_item_id);
CREATE TABLE promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_promotions PRIMARY KEY,
    code varchar(50) NOT NULL CONSTRAINT uq_promotions_code UNIQUE,
    discount_type varchar(20) NOT NULL,
    discount_value numeric(19,4) NOT NULL,
    valid_from timestamp(6) with time zone NOT NULL,
    valid_until timestamp(6) with time zone NOT NULL,
    minimum_order numeric(19,4) NOT NULL,
    usage_limit integer,
    status varchar(20) NOT NULL,
    CONSTRAINT chk_promotions_code CHECK(code=upper(btrim(code)) AND btrim(code)<>''),
    CONSTRAINT chk_promotions_type CHECK(discount_type IN ('FIXED','PERCENTAGE')),
    CONSTRAINT chk_promotions_value CHECK(discount_value>=0 AND discount_value<1000000000000000
        AND (discount_type<>'PERCENTAGE' OR discount_value<=100)),
    CONSTRAINT chk_promotions_window CHECK(isfinite(valid_from) AND isfinite(valid_until) AND valid_until>valid_from),
    CONSTRAINT chk_promotions_minimum CHECK(minimum_order>=0 AND minimum_order<1000000000000000),
    CONSTRAINT chk_promotions_usage CHECK(usage_limit IS NULL OR usage_limit>0),
    CONSTRAINT chk_promotions_status CHECK(status IN ('ACTIVE','INACTIVE'))
);
ALTER TABLE bookings ADD CONSTRAINT fk_bookings_promotion FOREIGN KEY(promotion_id) REFERENCES promotions(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE bookings DROP CONSTRAINT chk_bookings_pre_payment_stage;
ALTER TABLE bookings ADD CONSTRAINT chk_bookings_pre_payment_stage CHECK(status<>'PAID' AND payment_started_at IS NULL
    AND promotion_id IS NULL AND discount=0);

DO $migration$
DECLARE ns text:=current_schema(); source text; anchor text; ddl text:=$definitions$
-- Read-only predicate, always used after the gate/rows are locked by a controlled writer.
CREATE FUNCTION app.booking_composition_eligible(p_booking bigint) RETURNS boolean
LANGUAGE sql VOLATILE SET search_path=pg_catalog,pg_temp AS $body$
    SELECT EXISTS(SELECT 1 FROM app.bookings b JOIN app.showtimes s ON s.id=b.showtime_id
        JOIN app.halls h ON h.id=s.hall_id JOIN app.cinemas c ON c.id=h.cinema_id JOIN app.movies m ON m.id=s.movie_id
        JOIN app.users u ON u.id=b.customer_id
        WHERE b.id=p_booking AND b.status='PENDING' AND b.payment_started_at IS NULL AND b.expires_at>clock_timestamp()
        AND s.status='OPEN_FOR_BOOKING' AND s.start_time>clock_timestamp() AND s.booking_cut_off>clock_timestamp()
        AND h.status='ACTIVE' AND c.status='ACTIVE' AND m.status='PUBLISHED' AND u.status='ACTIVE' AND u.role='CUSTOMER'
        AND EXISTS(SELECT 1 FROM app.booking_seats WHERE booking_id=b.id)
        AND NOT EXISTS(SELECT 1 FROM app.booking_seats bs JOIN app.seats seat ON seat.id=bs.seat_id
            JOIN app.showtime_seats ss ON ss.showtime_id=bs.showtime_id AND ss.seat_id=bs.seat_id
            LEFT JOIN app.seat_holds sh ON sh.booking_id=b.id AND sh.seat_id=bs.seat_id
            WHERE bs.booking_id=b.id AND (NOT ss.is_sellable OR seat.physical_status<>'ACTIVE'
                OR sh.id IS NULL OR sh.status<>'ACTIVE' OR sh.expires_at<=clock_timestamp()
                OR sh.user_id<>b.customer_id OR bs.sold_at IS NOT NULL)))
$body$;

CREATE OR REPLACE FUNCTION app.guard_booking() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF current_user<>'smart_cinema_hold_owner' OR TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Protected Booking mutation';
    END IF;
    IF TG_OP='INSERT' THEN
        IF NEW.status<>'PENDING' OR NEW.expires_at<=clock_timestamp() OR NEW.concession_amount<>0 THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid initial Booking';
        END IF;
    ELSIF NEW.status=OLD.status THEN
        IF (to_jsonb(NEW)-ARRAY['concession_amount','subtotal','final_amount']) IS DISTINCT FROM
            (to_jsonb(OLD)-ARRAY['concession_amount','subtotal','final_amount'])
            OR NOT app.booking_composition_eligible(OLD.id) THEN
            RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking composition unavailable';
        END IF;
    ELSE
        IF (to_jsonb(NEW)-'status') IS DISTINCT FROM (to_jsonb(OLD)-'status')
            OR OLD.status<>'PENDING' OR NEW.status NOT IN ('CANCELLED','EXPIRED')
            OR (NEW.status='EXPIRED' AND NEW.expires_at>clock_timestamp()) THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Immutable Booking history';
        END IF;
    END IF;
    RETURN NEW;
END $body$;

CREATE FUNCTION app.guard_booking_concession() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_booking bigint;
BEGIN
    IF current_user<>'smart_cinema_hold_owner' THEN
        RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Protected Concession mutation';
    END IF;
    v_booking:=CASE WHEN TG_OP='DELETE' THEN OLD.booking_id ELSE NEW.booking_id END;
    IF NOT app.booking_composition_eligible(v_booking) THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking composition unavailable';
    END IF;
    IF TG_OP='INSERT' THEN
        IF NOT EXISTS(SELECT 1 FROM app.concession_items i WHERE i.id=NEW.concession_item_id AND i.status='ACTIVE'
            AND (i.name,i.category,i.selling_price)=(NEW.item_name_snapshot,NEW.category_snapshot,NEW.unit_price_snapshot)) THEN
            RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Concession unavailable';
        END IF;
    ELSIF TG_OP='UPDATE' THEN
        IF (to_jsonb(NEW)-ARRAY['quantity','total_price']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['quantity','total_price']) THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Immutable Concession snapshot';
        END IF;
    END IF;
    IF TG_OP='DELETE' THEN RETURN OLD; END IF;
    RETURN NEW;
END $body$;
CREATE TRIGGER trg_booking_concessions_guard BEFORE INSERT OR UPDATE OR DELETE ON app.booking_concessions
    FOR EACH ROW EXECUTE FUNCTION app.guard_booking_concession();
CREATE CONSTRAINT TRIGGER ct_booking_concession_composition AFTER INSERT OR UPDATE OR DELETE ON app.booking_concessions
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_booking();

CREATE FUNCTION app.guard_concession_catalog() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF current_user<>'smart_cinema_hold_owner' OR TG_OP='DELETE' THEN
        RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Protected Concession catalog';
    END IF;
    IF TG_OP='UPDATE' THEN
        IF (NEW.id,NEW.created_at) IS DISTINCT FROM (OLD.id,OLD.created_at) THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Immutable catalog identity';
        END IF;
        NEW.updated_at:=clock_timestamp();
    END IF;
    RETURN NEW;
END $body$;
CREATE TRIGGER trg_concession_items_guard BEFORE INSERT OR UPDATE OR DELETE ON app.concession_items
    FOR EACH ROW EXECUTE FUNCTION app.guard_concession_catalog();

-- Deployment-only configuration. No Admin HTTP API or seeded product/price is introduced.
CREATE FUNCTION app.configure_concession_item(p_id bigint,p_name text,p_description text,p_category text,p_price numeric,p_image text,p_status text)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_id bigint; v_now timestamptz:=clock_timestamp();
BEGIN
    IF p_price IS NULL OR p_price<0 OR p_price>=1000000000000000 OR p_price<>round(p_price,4) THEN
        RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='Invalid catalog price precision or range';
    END IF;
    IF p_id IS NULL THEN
        INSERT INTO app.concession_items(name,description,category,selling_price,image,status,created_at,updated_at)
            VALUES(p_name,p_description,p_category,p_price,p_image,p_status,v_now,v_now) RETURNING id INTO v_id;
    ELSE
        UPDATE app.concession_items SET name=p_name,description=p_description,category=p_category,selling_price=p_price,image=p_image,status=p_status
            WHERE id=p_id RETURNING id INTO v_id;
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Concession unavailable'; END IF;
    END IF;
    RETURN v_id;
END $body$;

CREATE FUNCTION app.edit_booking_concession(p_booking bigint,p_user bigint,p_line bigint,p_item bigint,p_quantity integer,p_operation text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_showtime bigint; v_item app.concession_items%ROWTYPE; v_line app.booking_concessions%ROWTYPE;
    v_price numeric; v_line_total numeric; v_total numeric; v_seat_amount numeric;
BEGIN
    IF p_operation IS NULL OR p_operation NOT IN ('ADD','UPDATE','REMOVE')
        OR (p_operation IN ('ADD','UPDATE') AND (p_quantity IS NULL OR p_quantity<=0))
        OR (p_operation='ADD' AND (p_item IS NULL OR p_item<=0 OR p_line IS NOT NULL))
        OR (p_operation<>'ADD' AND (p_line IS NULL OR p_line<=0 OR p_item IS NOT NULL)) THEN
        RAISE EXCEPTION USING ERRCODE='P0001',MESSAGE='Invalid Concession command';
    END IF;
    SELECT showtime_id INTO v_showtime FROM app.bookings WHERE id=p_booking AND customer_id=p_user;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Booking unavailable'; END IF;
    PERFORM app.lock_hold_context(v_showtime,p_user);
    PERFORM app.lock_booking_resources(v_showtime);
    PERFORM app.expire_booking_aggregates(v_showtime);
    IF NOT app.booking_composition_eligible(p_booking) THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking composition unavailable';
    END IF;
    IF p_operation='ADD' THEN
        SELECT * INTO v_item FROM app.concession_items WHERE id=p_item AND status='ACTIVE' FOR SHARE;
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Concession unavailable'; END IF;
        v_price:=v_item.selling_price;
    ELSE
        SELECT * INTO v_line FROM app.booking_concessions WHERE id=p_line AND booking_id=p_booking FOR UPDATE;
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Concession line unavailable'; END IF;
        v_price:=v_line.unit_price_snapshot;
    END IF;
    v_line_total:=CASE WHEN p_operation='REMOVE' THEN 0 ELSE v_price*p_quantity END;
    SELECT coalesce(sum(total_price),0) INTO v_total FROM app.booking_concessions WHERE booking_id=p_booking;
    v_total:=v_total-coalesce(v_line.total_price,0)+v_line_total;
    SELECT seat_amount INTO v_seat_amount FROM app.bookings WHERE id=p_booking;
    IF v_line_total>=1000000000000000 OR v_total>=1000000000000000 OR v_total+v_seat_amount>=1000000000000000 THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking amount exceeds supported bounds';
    END IF;
    IF p_operation='ADD' THEN
        INSERT INTO app.booking_concessions(booking_id,concession_item_id,item_name_snapshot,category_snapshot,quantity,unit_price_snapshot,total_price)
            VALUES(p_booking,p_item,v_item.name,v_item.category,p_quantity,v_price,v_line_total);
    ELSIF p_operation='UPDATE' THEN
        UPDATE app.booking_concessions SET quantity=p_quantity,total_price=v_line_total WHERE id=p_line;
    ELSE
        DELETE FROM app.booking_concessions WHERE id=p_line;
    END IF;
    UPDATE app.bookings SET concession_amount=v_total,subtotal=seat_amount+v_total,final_amount=seat_amount+v_total WHERE id=p_booking;
    IF NOT app.booking_composition_eligible(p_booking) THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking composition expired';
    END IF;
END $body$;

ALTER TABLE app.concession_items OWNER TO smart_cinema_hold_owner;
ALTER TABLE app.booking_concessions OWNER TO smart_cinema_hold_owner;
ALTER TABLE app.promotions OWNER TO smart_cinema_hold_owner;
REVOKE ALL ON app.concession_items,app.booking_concessions,app.promotions FROM PUBLIC;
GRANT SELECT ON app.concession_items,app.booking_concessions TO smart_cinema_hold_runtime;
ALTER FUNCTION app.booking_composition_eligible(bigint) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.guard_booking_concession() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.guard_concession_catalog() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.configure_concession_item(bigint,text,text,text,numeric,text,text) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.edit_booking_concession(bigint,bigint,bigint,bigint,integer,text) OWNER TO smart_cinema_hold_owner;
REVOKE ALL ON FUNCTION app.booking_composition_eligible(bigint),app.guard_booking_concession(),app.guard_concession_catalog(),
    app.configure_concession_item(bigint,text,text,text,numeric,text,text),app.edit_booking_concession(bigint,bigint,bigint,bigint,integer,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.edit_booking_concession(bigint,bigint,bigint,bigint,integer,text) TO smart_cinema_hold_runtime;
$definitions$;
BEGIN
    EXECUTE replace(ddl,'app.',format('%I.',ns));
    source:=pg_get_functiondef(format('%I.assert_booking()',ns)::regprocedure);
    anchor:='IF NOT EXISTS(SELECT 1 FROM';
    IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected V6 aggregate assertion'; END IF;
    source:=replace(source,anchor,format('IF b.concession_amount<>(SELECT coalesce(sum(total_price),0) FROM %I.booking_concessions WHERE booking_id=v_id) OR NOT EXISTS(SELECT 1 FROM',ns));
    EXECUTE source;
    source:=pg_get_functiondef(format('%I.guard_booking_seat()',ns)::regprocedure);
    anchor:='WHERE b.id=NEW.booking_id AND b.xmin=pg_current_xact_id()::xid';
    IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected V6 Seat line guard'; END IF;
    -- Header totals now change xmin: a committed aggregate always has attached origin Holds.
    -- All initial Seat lines are inserted before the first attachment in create_booking.
    source:=replace(source,anchor,anchor||format(' AND NOT EXISTS(SELECT 1 FROM %I.seat_holds origin WHERE origin.booking_id=b.id)',ns));
    EXECUTE source;
END $migration$;
