-- Internal initiation only. Provider/currency binding and any charge are deferred.
CREATE TABLE payment_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_payment_transactions PRIMARY KEY,
    booking_id bigint NOT NULL CONSTRAINT fk_payment_transactions_booking REFERENCES bookings(id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    provider varchar(50),
    internal_reference varchar(100) NOT NULL CONSTRAINT uq_payment_transactions_internal_reference UNIQUE,
    external_reference varchar(255),
    amount numeric(19,4) NOT NULL,
    currency varchar(3),
    status varchar(20) NOT NULL DEFAULT 'INITIATED',
    initiated_at timestamp(6) with time zone NOT NULL,
    completed_at timestamp(6) with time zone,
    provider_metadata jsonb NOT NULL DEFAULT '{}',
    CONSTRAINT uq_payment_transactions_provider_external UNIQUE(provider,external_reference),
    CONSTRAINT chk_payment_transactions_reference CHECK(btrim(internal_reference)<>''),
    CONSTRAINT chk_payment_transactions_amount CHECK(amount>=0 AND amount<1000000000000000),
    CONSTRAINT chk_payment_transactions_time CHECK(isfinite(initiated_at)),
    -- No invented provider/currency, result transition or submission capability.
    CONSTRAINT chk_payment_transactions_initiation_stage CHECK(status='INITIATED' AND completed_at IS NULL
        AND provider IS NULL AND currency IS NULL AND external_reference IS NULL AND provider_metadata='{}'::jsonb)
);
CREATE UNIQUE INDEX uq_payment_transactions_unresolved_booking ON payment_transactions(booking_id)
    WHERE status IN ('INITIATED','PENDING');
CREATE INDEX idx_payment_transactions_booking ON payment_transactions(booking_id,id);
ALTER TABLE bookings DROP CONSTRAINT chk_bookings_pre_payment_stage;
ALTER TABLE bookings ADD CONSTRAINT chk_bookings_pre_payment_stage CHECK(status<>'PAID');

DO $migration$
DECLARE ns text:=current_schema(); source text; anchor text; replacement text; ddl text:=$definitions$
-- No changes to snapshots: if current Promotion terms differ, explicitly reapply before initiation.
CREATE FUNCTION app.validate_payment_composition(p_booking bigint) RETURNS void
LANGUAGE plpgsql VOLATILE SET search_path=pg_catalog,pg_temp AS $body$
DECLARE b app.bookings%ROWTYPE; p app.promotions%ROWTYPE; v_discount numeric; v_used bigint;
BEGIN
    SELECT * INTO b FROM app.bookings WHERE id=p_booking;
    IF NOT app.booking_composition_eligible(p_booking) THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking unavailable for initiation';
    END IF;
    IF b.seat_amount<>(SELECT coalesce(sum(final_price),0) FROM app.booking_seats WHERE booking_id=b.id)
        OR b.concession_amount<>(SELECT coalesce(sum(total_price),0) FROM app.booking_concessions WHERE booking_id=b.id)
        OR b.subtotal<>b.seat_amount+b.concession_amount OR b.final_amount<>b.subtotal-b.discount THEN
        RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Inconsistent Booking totals';
    END IF;
    IF b.promotion_id IS NOT NULL THEN
        SELECT * INTO p FROM app.promotions WHERE id=b.promotion_id FOR UPDATE;
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0005',MESSAGE='Promotion unavailable'; END IF;
        SELECT count(*) INTO v_used FROM app.bookings WHERE promotion_id=p.id AND status='PAID';
        v_discount:=app.promotion_discount(p,b.subtotal,v_used);
        IF v_discount<>b.discount OR (p.code,p.discount_type,p.discount_value,p.minimum_order,p.max_discount_amount)
            IS DISTINCT FROM (b.promotion_code_snapshot,b.promotion_type_snapshot,b.promotion_value_snapshot,
                b.promotion_minimum_snapshot,b.promotion_cap_snapshot) THEN
            RAISE EXCEPTION USING ERRCODE='P0006',MESSAGE='Promotion terms changed; review composition';
        END IF;
    END IF;
    IF NOT app.booking_composition_eligible(p_booking) THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking expired during initiation';
    END IF;
END $body$;

CREATE FUNCTION app.guard_payment_transaction() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
BEGIN
    IF current_user<>'smart_cinema_hold_owner' OR TG_OP<>'INSERT' THEN
        RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Immutable initiated Payment';
    END IF;
    PERFORM app.validate_payment_composition(NEW.booking_id);
    IF NOT EXISTS(SELECT 1 FROM app.bookings WHERE id=NEW.booking_id AND payment_started_at IS NULL
        AND final_amount=NEW.amount AND created_at<=NEW.initiated_at AND NEW.initiated_at<expires_at)
        OR NEW.initiated_at>clock_timestamp() THEN
        RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Invalid Payment origin';
    END IF;
    RETURN NEW;
END $body$;
CREATE TRIGGER trg_payment_transactions_guard BEFORE INSERT OR UPDATE OR DELETE ON app.payment_transactions
    FOR EACH ROW EXECUTE FUNCTION app.guard_payment_transaction();

CREATE FUNCTION app.assert_payment_freeze() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_id bigint; b app.bookings%ROWTYPE; v_count bigint;
BEGIN
    IF TG_TABLE_NAME='bookings' THEN v_id:=coalesce(NEW.id,OLD.id); ELSE v_id:=coalesce(NEW.booking_id,OLD.booking_id); END IF;
    SELECT * INTO b FROM app.bookings WHERE id=v_id;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Missing Payment Booking'; END IF;
    SELECT count(*) INTO v_count FROM app.payment_transactions WHERE booking_id=v_id;
    IF (b.payment_started_at IS NULL AND v_count<>0)
        OR (b.payment_started_at IS NOT NULL AND (v_count<>1 OR NOT EXISTS(
            SELECT 1 FROM app.payment_transactions WHERE booking_id=v_id AND initiated_at=b.payment_started_at AND amount=b.final_amount))) THEN
        RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Payment attempt and freeze must commit together';
    END IF;
    RETURN NULL;
END $body$;
CREATE CONSTRAINT TRIGGER ct_payment_transactions_freeze AFTER INSERT OR UPDATE OR DELETE ON app.payment_transactions
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_payment_freeze();
CREATE CONSTRAINT TRIGGER ct_bookings_payment_freeze AFTER INSERT OR UPDATE OR DELETE ON app.bookings
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION app.assert_payment_freeze();

CREATE FUNCTION app.initiate_payment(p_booking bigint,p_user bigint) RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $body$
DECLARE v_showtime bigint; b app.bookings%ROWTYPE; v_id bigint; v_now timestamptz;
BEGIN
    SELECT showtime_id INTO v_showtime FROM app.bookings WHERE id=p_booking AND customer_id=p_user;
    IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='P0002',MESSAGE='Booking unavailable'; END IF;
    PERFORM app.lock_hold_context(v_showtime,p_user);
    PERFORM app.lock_booking_resources(v_showtime);
    PERFORM app.expire_booking_aggregates(v_showtime);
    SELECT * INTO b FROM app.bookings WHERE id=p_booking;
    IF b.status<>'PENDING' OR b.expires_at<=clock_timestamp() THEN
        RAISE EXCEPTION USING ERRCODE='P0003',MESSAGE='Booking unavailable for initiation';
    END IF;
    IF b.payment_started_at IS NOT NULL THEN
        -- Recovery only, not a fresh eligibility/charge authorization or a reprice.
        SELECT id INTO v_id FROM app.payment_transactions WHERE booking_id=p_booking AND status='INITIATED';
        IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Missing unresolved Payment'; END IF;
        RETURN v_id;
    END IF;
    PERFORM app.validate_payment_composition(p_booking);
    v_now:=clock_timestamp();
    INSERT INTO app.payment_transactions(booking_id,internal_reference,amount,initiated_at)
        VALUES(p_booking,'P-'||replace(gen_random_uuid()::text,'-',''),b.final_amount,v_now) RETURNING id INTO v_id;
    UPDATE app.bookings SET payment_started_at=v_now WHERE id=p_booking;
    RETURN v_id;
END $body$;

ALTER TABLE app.payment_transactions OWNER TO smart_cinema_hold_owner;
REVOKE ALL ON app.payment_transactions FROM PUBLIC;
GRANT SELECT ON app.payment_transactions TO smart_cinema_hold_runtime;
ALTER FUNCTION app.validate_payment_composition(bigint) OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.guard_payment_transaction() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.assert_payment_freeze() OWNER TO smart_cinema_hold_owner;
ALTER FUNCTION app.initiate_payment(bigint,bigint) OWNER TO smart_cinema_hold_owner;
REVOKE ALL ON FUNCTION app.validate_payment_composition(bigint),app.guard_payment_transaction(),
    app.assert_payment_freeze(),app.initiate_payment(bigint,bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.initiate_payment(bigint,bigint) TO smart_cinema_hold_runtime;
$definitions$;
BEGIN
    EXECUTE replace(ddl,'app.',format('%I.',ns));
    source:=pg_get_functiondef(format('%I.guard_booking()',ns)::regprocedure);
    anchor:='ELSIF NEW.status=OLD.status THEN';
    IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected V8 Booking guard'; END IF;
    replacement:=format($text$
    ELSIF OLD.payment_started_at IS NULL AND NEW.payment_started_at IS NOT NULL THEN
        IF (to_jsonb(NEW)-'payment_started_at') IS DISTINCT FROM (to_jsonb(OLD)-'payment_started_at') THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Freeze cannot change composition';
        END IF;
        PERFORM %1$I.validate_payment_composition(OLD.id);
        IF NOT EXISTS(SELECT 1 FROM %1$I.payment_transactions WHERE booking_id=OLD.id
            AND initiated_at=NEW.payment_started_at AND amount=OLD.final_amount) THEN
            RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='Freeze requires persisted Payment attempt';
        END IF;
    ELSIF NEW.status=OLD.status THEN
$text$,ns);
    source:=replace(source,anchor,replacement);
    -- Initial Booking creation cannot smuggle in a freeze; terminal transitions already preserve all other columns.
    anchor:='IF NEW.status<>''PENDING'' OR NEW.expires_at<=clock_timestamp()';
    IF position(anchor IN source)=0 THEN RAISE EXCEPTION 'Unexpected V8 initial Booking guard'; END IF;
    source:=replace(source,anchor,'IF NEW.payment_started_at IS NOT NULL OR NEW.status<>''PENDING'' OR NEW.expires_at<=clock_timestamp()');
    EXECUTE source;
END $migration$;
