spring.application.name=smart-cinema-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/smart_cinema}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-migration-naming=true

auth.jwt.secret=KUwatf3M+AKypyAF0xOxIQiB8Y0DsL4SsZyBf0I8K7Y=
auth.jwt.access-token-ttl=PT15M
auth.jwt.refresh-token-ttl=${AUTH_REFRESH_TOKEN_TTL:P30D}
